[patch] Fail task when embedded command fails (#1104)

diff --git a/image/cli/mascli/functions/gitops_mongo b/image/cli/mascli/functions/gitops_mongo
--- a/image/cli/mascli/functions/gitops_mongo
+++ b/image/cli/mascli/functions/gitops_mongo
@@ -184,6 +184,9 @@ function gitops_mongo() {
     gitops_mongo_interactive
   fi
 
+  # catch errors
+  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR
+
   echo
   reset_colors
   echo_h2 "Review Settings"
diff --git a/image/cli/mascli/functions/gitops_process_mongo_user b/image/cli/mascli/functions/gitops_process_mongo_user
--- a/image/cli/mascli/functions/gitops_process_mongo_user
+++ b/image/cli/mascli/functions/gitops_process_mongo_user
@@ -192,6 +192,9 @@ function gitops_process_mongo_user() {
     exit 1
     gitops_process_mongo_user_interactive
   fi
+  
+  # catch errors
+  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR
 
   echo
   reset_colors
