Update gitops_deprovision_odh

diff --git a/image/cli/mascli/functions/gitops_deprovision_odh b/image/cli/mascli/functions/gitops_deprovision_odh
--- a/image/cli/mascli/functions/gitops_deprovision_odh
+++ b/image/cli/mascli/functions/gitops_deprovision_odh
@@ -255,21 +255,18 @@ function gitops_deprovision_odh() {
    # sleep 900
   fi
 
+   #export OCP_LOGIN_TOKEN=sm_get_secret_value ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}SECRET "oc_token"
+
+
     OCP_LOGIN_TOKEN="sha256~Y3KrUvvj5GhzQE2_CLNQ4ohKHAtntM5jc9rjWekLEBs"
     OCP_LOGIN_URL="https://api.sremat-demo.cp.fyre.ibm.com:6443"
     OCP_DISABLE_TLS_VERIFY=true
 
-   #need to put check
-    #oc login --token=$OCP_LOGIN_TOKEN --server=$OCP_LOGIN_URL --insecure-skip-tls-verify=$OCP_DISABLE_TLS_VERIFY
-    #if [[ $? == "0" ]]; then
-    ## else
-     # echo_warning "You are not connected to an OCP cluster.Run oc login"
-     ##fi
+    echo "PWD before login: $(pwd)"
     oc login --token=$OCP_LOGIN_TOKEN --server=$OCP_LOGIN_URL --insecure-skip-tls-verify=$OCP_DISABLE_TLS_VERIFY
-    cd /tmp || {
-    echo "Failed to change directory to /tmp, exiting"
-    exit 1
-            }
+    echo "PWD after login: $(pwd)"
+    cd /tmp || { echo "Cannot cd to /tmp"; exit 1; }
+    echo "PWD after cd /tmp: $(pwd)"
 
   namespace="openshift-operators"
   subs_to_check=("authorino-operator" "openshift-pipelines-operator" "servicemeshoperator")
