delete branch code added after every failure

diff --git a/image/cli/mascli/functions/gitops_iac b/image/cli/mascli/functions/gitops_iac
--- a/image/cli/mascli/functions/gitops_iac
+++ b/image/cli/mascli/functions/gitops_iac
@@ -1515,13 +1515,19 @@ function gitops_iac_manage_pr() {
   
   if [[ $? -ne 0 ]]; then
     echo " Failed to create Pull Request"
+    delete_remote_branch "${WORKING_BRANCH}" "$GITOPS_WORKING_DIR/$GITHUB_REPO"
     exit 1
   fi
   
   echo "Created PR #${PR_NUMBER}"
   
-  # Clean up local clone
-  remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO
+  # Set up automatic cleanup on exit
+  cleanup_gitops_repo() {
+    if [[ -d "$GITOPS_WORKING_DIR/$GITHUB_REPO" ]]; then
+      remove_git_repo_clone "$GITOPS_WORKING_DIR/$GITHUB_REPO"
+    fi
+  }
+  trap cleanup_gitops_repo EXIT
   
   # Monitor PR status if PR was created
   if [[ -n "${PR_NUMBER}" && "${PR_NUMBER}" != "null" ]]; then
@@ -1554,29 +1560,34 @@ function gitops_iac_manage_pr() {
             echo_h2 "  Atlantis Apply Failed. Pipeline Failed."
             comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "atlantis unlock"
             close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
+            delete_remote_branch "$WORKING_BRANCH" "$GITOPS_WORKING_DIR/$GITHUB_REPO"
             exit 1
           fi
         else
           echo_h2 "  Failed to add 'Atlantis Apply' on PR. PIPELINE FAILED. CLOSING PR."
           comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "atlantis unlock"
           close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
+          delete_remote_branch "$WORKING_BRANCH" "$GITOPS_WORKING_DIR/$GITHUB_REPO"
           exit 1
         fi
       else
         echo_h2 "  Failed to approve PR. Closing PR. Pipeline Failed."
         comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "atlantis unlock"
         close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
+        delete_remote_branch "$WORKING_BRANCH" "$GITOPS_WORKING_DIR/$GITHUB_REPO"
         exit 1
       fi
     else
       echo_h2 "  Atlantis Plan Failed. Closing PR. Pipeline Failed."
       comment_on_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER" "atlantis unlock"
       close_pr "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$PR_NUMBER"
+      delete_remote_branch "$WORKING_BRANCH" "$GITOPS_WORKING_DIR/$GITHUB_REPO"
       exit 1
     fi
   else
     echo
     echo_h2 "  No PR number returned, pipeline failed."
+    delete_remote_branch "$WORKING_BRANCH" "$GITOPS_WORKING_DIR/$GITHUB_REPO"
     exit 1
   fi
   
diff --git a/image/cli/mascli/functions/gitops_utils b/image/cli/mascli/functions/gitops_utils
--- a/image/cli/mascli/functions/gitops_utils
+++ b/image/cli/mascli/functions/gitops_utils
@@ -382,6 +382,32 @@ function unlock_git_repo() {
     echo "-------------------------------------------------"
     rm -rf "${GITOPS_REPO_DIR}" || exit 1
   fi
+
+# Delete a branch from remote Git repository
+# Parameters:
+#   $1 - BRANCH_NAME: Name of the branch to delete from remote
+#   $2 - GITOPS_REPO_DIR: Local directory path of the Git repository
+function delete_remote_branch() {
+  BRANCH_NAME=$1
+  GITOPS_REPO_DIR=$2
+
+  if [[ -z "${BRANCH_NAME}" ]]; then
+    echo "$(logts) ERROR: Branch name is required"
+    exit 1
+  fi
+
+  if [[ ! -d "${GITOPS_REPO_DIR}" ]]; then
+    echo "$(logts) ERROR: Repository directory does not exist: ${GITOPS_REPO_DIR}"
+    exit 1
+  fi
+
+  echo ""
+  echo "$(logts) git push origin --delete ${BRANCH_NAME}"
+  echo "-------------------------------------------------"
+  git -C "${GITOPS_REPO_DIR}" push origin --delete "${BRANCH_NAME}" || exit 1
+
+  echo "$(logts) Remote branch '${BRANCH_NAME}' deleted successfully"
+}
 }
 
 
