Msk pipeline and task changes

diff --git a/image/cli/mascli/functions/gitops_iac b/image/cli/mascli/functions/gitops_iac
--- a/image/cli/mascli/functions/gitops_iac
+++ b/image/cli/mascli/functions/gitops_iac
@@ -303,6 +303,110 @@ function gitops_iac_noninteractive() {
         fi
         ;;
 
+      --msk_source)
+        export MSK_SOURCE=$1 && shift
+        ;;
+
+      --iot_msk_kafka_version)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export IOT_MSK_KAFKA_VERSION=$1
+          shift
+        else
+          export IOT_MSK_KAFKA_VERSION=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --iot_msk_instance_type)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export IOT_MSK_INSTANCE_TYPE=$1
+          shift
+        else
+          export IOT_MSK_INSTANCE_TYPE=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --iot_msk_cluster_username)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export IOT_MSK_CLUSTER_USERNAME=$1
+          shift
+        else
+          export IOT_MSK_CLUSTER_USERNAME=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --iot_broker_volume_size)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export IOT_BROKER_VOLUME_SIZE=$1
+          shift
+        else
+          export IOT_BROKER_VOLUME_SIZE=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --iot_number_of_broker_nodes)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export IOT_NUMBER_OF_BROKER_NODES=$1
+          shift
+        else
+          export IOT_NUMBER_OF_BROKER_NODES=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --monitor_msk_kafka_version)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export MONITOR_MSK_KAFKA_VERSION=$1
+          shift
+        else
+          export MONITOR_MSK_KAFKA_VERSION=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --monitor_msk_instance_type)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export MONITOR_MSK_INSTANCE_TYPE=$1
+          shift
+        else
+          export MONITOR_MSK_INSTANCE_TYPE=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --monitor_msk_cluster_username)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export MONITOR_MSK_CLUSTER_USERNAME=$1
+          shift
+        else
+          export MONITOR_MSK_CLUSTER_USERNAME=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --monitor_broker_volume_size)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export MONITOR_BROKER_VOLUME_SIZE=$1
+          shift
+        else
+          export MONITOR_BROKER_VOLUME_SIZE=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
+      --monitor_number_of_broker_nodes)
+        if [[ -n "$1" && "$1" != --* ]]; then
+          export MONITOR_NUMBER_OF_BROKER_NODES=$1
+          shift
+        else
+          export MONITOR_NUMBER_OF_BROKER_NODES=""
+          [[ $# -gt 0 ]] && shift
+        fi
+        ;;
+
       # Target Cluster (Optional)
       --cluster-url)
         export CLUSTER_URL=$1 && shift
@@ -463,6 +567,33 @@ function compute_s3_variables() {
   echo "  S3_MANAGE: ${S3_MANAGE}"
   echo "  S3_MVI: ${S3_MVI}"
   echo "  VPC_ID: ${VPC_ID_VALUE}"s
+
+  echo " S3 variables computed successfully"
+}
+
+# Compute msk-related variables from cluster configuration files
+# This function extracts values from existing Terraform files
+function compute_msk_variables() {
+  local TASK_WORKING_DIR=$1
+  local GITHUB_REPO=$2
+  local REGION_NAME=$3
+  local CLUSTER_ID=$4
+
+  echo "Computing S3 variables..."
+
+  # Extract values from cluster files
+  CLUSTER_PATH=${TASK_WORKING_DIR}/${GITHUB_REPO}/${REGION_NAME}/clusters/${CLUSTER_ID}
+  TERRAFORMTF_FILE_PATH=$CLUSTER_PATH/terraform.tfvars
+  MAIN_FILE_PATH=$CLUSTER_PATH/main.tf
+
+  # Compute S3 variables from Terraform files
+  export NAME_PREFIX_VALUE=$(get_tf_value "${TERRAFORMTF_FILE_PATH}" "name_prefix")
+  export VPC_ID_VALUE=$(get_tf_value "${TERRAFORMTF_FILE_PATH}" "vpc_id")
+  export SECURITY_GROUPS_VALUE=$(get_tf_value "${MAIN_FILE_PATH}" "locals.cluster.security_groups")
+
+  echo "  NAME_PREFIX_VALUE: ${NAME_PREFIX_VALUE}"
+  echo "  VPC_ID: ${VPC_ID_VALUE}"
+  echo "  SECURITY_GROUPS_VALUE: ${SECURITY_GROUPS_VALUE}"
 
   echo " S3 variables computed successfully"
 }
@@ -700,6 +831,82 @@ function gitops_iac_provision_s3() {
   exit 0
 }
 
+function gitops_iac_provision_msk(){
+  echo
+  echo_h2 "Creating MSK Resources terraform files"
+
+  # Validate required parameters
+  [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_iac_help "GITOPS_WORKING_DIR is not set"
+  [[ -z "$GITHUB_REPO" ]] && gitops_iac_help "GITHUB_REPO is not set"
+  [[ -z "$REGION_NAME" ]] && gitops_iac_help "REGION_NAME is not set"
+  [[ -z "$MAS_INSTANCE_ID" ]] && gitops_iac_help "MAS_INSTANCE_ID is not set"
+  [[ -z "$CLUSTER_ID" ]] && gitops_iac_help "CLUSTER_ID is not set"
+  [[ -z "$GITHUB_PUSH" ]] && export GITHUB_PUSH=true
+
+  # Read the working branch name created by previous task
+  if [ -f "${GITOPS_WORKING_DIR}/new_branch_name.txt" ]; then
+    WORKING_BRANCH=$(cat ${GITOPS_WORKING_DIR}/new_branch_name.txt)
+    echo "Using working branch: ${WORKING_BRANCH}"
+  else
+    echo "ERROR: Branch name file not found. Run gitops_iac_create_branch first."
+    exit 1
+  fi
+
+  # Clone the working branch to get latest changes from other tasks
+  if [ -z $GIT_SSH ]; then
+    export GIT_SSH=false
+  fi
+
+  # Use a unique subdirectory for this task to avoid conflicts with parallel tasks
+  TASK_WORKING_DIR="${GITOPS_WORKING_DIR}/msk-task"
+  mkdir -p ${TASK_WORKING_DIR}
+
+  # Remove any existing clone first with force
+  if [ -d "${TASK_WORKING_DIR}/${GITHUB_REPO}" ]; then
+    echo
+    echo_h2 "Removing existing repository clone"
+    chmod -R +w ${TASK_WORKING_DIR}/${GITHUB_REPO} 2>/dev/null || true
+    rm -rf ${TASK_WORKING_DIR}/${GITHUB_REPO}
+    sleep 1
+  fi
+
+  echo
+  echo_h2 "Cloning working branch ${WORKING_BRANCH} to get latest changes"
+  clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $WORKING_BRANCH $TASK_WORKING_DIR $GIT_SSH
+
+  GITOPS_CLUSTER_DIR=${TASK_WORKING_DIR}/${GITHUB_REPO}/${REGION_NAME}/instances/${MAS_INSTANCE_ID}
+  mkdir -p ${GITOPS_CLUSTER_DIR}
+
+  echo
+  echo_h2 "Generating IAC/MSK Configuration"
+
+  # S3_MANAGE and S3_MVI are already set from command-line parameters
+  echo "MONITOR_MSK_CLUSTER_USERNAME: ${MONITOR_MSK_CLUSTER_USERNAME}"
+  echo "MONITOR_MSK_CLUSTER_USERNAME: ${MONITOR_MSK_CLUSTER_USERNAME}"
+
+  echo "Generating msk.tf file ${GITOPS_CLUSTER_DIR}/msk.tf "
+  jinjanate_commmon $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-iac-msk.yaml.j2 ${GITOPS_CLUSTER_DIR}/msk.tf
+
+  # Commit changes to working branch
+  if [ "$GITHUB_PUSH" == "true" ]; then
+    echo
+    echo_h2 "Committing msk changes to branch ${WORKING_BRANCH}"
+    GIT_COMMIT_MSG="Add msk configuration"
+    save_to_target_git_repo "$GITHUB_HOST" "$GITHUB_ORG" "$GITHUB_REPO" "$WORKING_BRANCH" "${TASK_WORKING_DIR}/${GITHUB_REPO}" "${GIT_COMMIT_MSG}"
+  fi
+
+  echo
+  echo_h2 " MSK Resources terraform files are Committed"
+
+  # Clean up cloned repository
+  echo
+  echo_h2 "Cleaning up local repository clone"
+  chmod -R +w ${TASK_WORKING_DIR}/${GITHUB_REPO} 2>/dev/null || true
+  rm -rf ${TASK_WORKING_DIR}/${GITHUB_REPO}
+
+  exit 0
+}
+
 # ============================================================================
 # Function 4: Generate Common IAC Files
 # ============================================================================
@@ -768,6 +975,12 @@ function gitops_iac_generate_common_files() {
     echo
     echo_h2 "Computing S3 Variables"
     compute_s3_variables "${TASK_WORKING_DIR}" "${GITHUB_REPO}" "${REGION_NAME}" "${CLUSTER_ID}"
+  fi
+
+  if [[ "$IS_MSK" == "true" ]]; then
+    echo
+    echo_h2 "Computing MSK Variables"
+    compute_msk_variables "${TASK_WORKING_DIR}" "${GITHUB_REPO}" "${REGION_NAME}" "${CLUSTER_ID}"
   fi
   
   echo "Checking and creating common files"
@@ -1006,6 +1219,19 @@ function gitops_iac_provision_s3_cmd() {
   
   # Call the actual function
   gitops_iac_provision_s3
+}
+
+function gitops_iac_provision_msk_cmd() {
+  shift  # Remove command name
+  if [[ $# -gt 0 ]]; then
+    gitops_iac_noninteractive "$@"
+  else
+    echo "Not supported yet"
+    exit 1
+  fi
+
+  # Call the actual function
+  gitops_iac_provision_msk
 }
 
 # Wrapper for gitops-iac-generate-common-files command
