{patch] test another approach

diff --git a/image/cli/mascli/functions/gitops_suite b/image/cli/mascli/functions/gitops_suite
--- a/image/cli/mascli/functions/gitops_suite
+++ b/image/cli/mascli/functions/gitops_suite
@@ -330,7 +330,6 @@ function gitops_suite_noninteractive() {
 }
 
 function gitops_suite() {
-  set -e
   # Take the first parameter off (it will be create-gitops)
   shift
   if [[ $# -gt 0 ]]; then
@@ -587,13 +586,13 @@ function gitops_suite() {
   echo_h2 "Generating Argo Project and Applications"
 
   echo "- Base Config"
-  jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-instance-base.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-instance-base.yaml
+  jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-instance-base.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-instance-base.yaml || { echo "Error occurred"; exit 1; }
 
   echo "- IBM Suite License Service"
-  jinja -X .+ -d $MONGO_CONFIG_FILE $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-sls-fake.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-sls.yaml
+  jinja -X .+ -d $MONGO_CONFIG_FILE $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-sls-fake.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-sls.yaml || { echo "Error occurred"; exit 1; }
 
   echo "- IBM Maximo Application Suite Core Platform"
-  jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-suite.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-suite.yaml
+  jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-suite.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-suite.yaml || { echo "Error occurred"; exit 1; }
 
 
   # Commit and push to github target repo
