[patch] test catching error

diff --git a/image/cli/mascli/functions/gitops_suite b/image/cli/mascli/functions/gitops_suite
--- a/image/cli/mascli/functions/gitops_suite
+++ b/image/cli/mascli/functions/gitops_suite
@@ -335,8 +335,6 @@ function gitops_suite_noninteractive() {
 }
 
 function gitops_suite() {
-  trap "{ echo 'Error occurred on line $LINENO while running command $BASH_COMMAND'; exit 1; }" ERR
-
   # Take the first parameter off (it will be create-gitops)
   shift
   if [[ $# -gt 0 ]]; then
@@ -603,7 +601,7 @@ function gitops_suite() {
   jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-instance-base.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-instance-base.yaml
 
   echo "- IBM Suite License Service"
-  jinja -X .+ -d $MONGO_CONFIG_FILE $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-sls-fake.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-sls.yaml
+  jinja -X .+ -d $MONGO_CONFIG_FILE $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-sls.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-sls.yaml || { echo "Error occurred on line $LINENO"; exit 1; }
 
   echo "- IBM Maximo Application Suite Core Platform"
   jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/ibm-mas-suite.yaml.j2 -o ${GITOPS_INSTANCE_DIR}/ibm-mas-suite.yaml
