[patch][mascore-1701] validate argo app name lengths

diff --git a/image/cli/mascli/functions/gitops_utils b/image/cli/mascli/functions/gitops_utils
--- a/image/cli/mascli/functions/gitops_utils
+++ b/image/cli/mascli/functions/gitops_utils
@@ -575,3 +575,12 @@ function check_argo_app_healthy() {
     fi
   done
 }
+
+function validate_app_name(){
+  APPLICATION=$1
+
+  if [[ ${#APPLICATION} -gt 63 ]]; then
+    echo "Application name cannot be longer than 63 characters: $APPLICATION"
+    exit 1
+  fi
+}
