Progressing SaaS gitops POC (#797)

diff --git a/image/cli/mascli/functions/gitops_db2u_database b/image/cli/mascli/functions/gitops_db2u_database
--- a/image/cli/mascli/functions/gitops_db2u_database
+++ b/image/cli/mascli/functions/gitops_db2u_database
@@ -75,6 +75,13 @@ function gitops_db2u_database_noninteractive() {
   GIT_COMMIT_MSG="gitops-db2u-database commit"
   export GITOPS_VERSION=${GITOPS_VERSION:-poc}
 
+  # TODO: will need to add explicit args to pipeline when we start using this code to deploy to MCSP
+  export REGION=${REGION:-${SM_AWS_REGION}}
+  export CLUSTER_URL=${CLUSTER_URL:-"https://kubernetes.default.svc"} # use an in-cluster argocd worker (which fvtsaas does)
+  # alternatively for CLUSTER_URL, we could look it up from ArgoCD like this:
+  # export CLUSTER_URL
+  # argocd_get_cluster_url "${CLUSTER_ID}" "CLUSTER_URL"
+
   while [[ $# -gt 0 ]]
   do
     key="$1"
@@ -92,6 +99,12 @@ function gitops_db2u_database_noninteractive() {
         ;;
       -c|--cluster-id)
         export CLUSTER_ID=$1 && shift
+        ;;
+      -r|--region)
+        export REGION=$1 && shift
+        ;;
+      -u|--cluster-url)
+        export CLUSTER_URL=$1 && shift
         ;;
 
       # MAS
@@ -247,6 +260,7 @@ function gitops_db2u_database_noninteractive() {
 
   [[ -z "$GITOPS_WORKING_DIR" ]] && gitops_db2u_database_help "GITOPS_WORKING_DIR is not set"
   [[ -z "$ACCOUNT_ID" ]] && gitops_db2u_database_help "ACCOUNT_ID is not set"
+  [[ -z "$REGION" ]] && gitops_db2u_database_help "REGION is not set"
   [[ -z "$CLUSTER_ID" ]] && gitops_db2u_database_help "CLUSTER_ID is not set"
   
   #db2u
@@ -271,94 +285,6 @@ function gitops_db2u_database_noninteractive() {
 
 }
 
-function wait_for_db2ucluster_crd(){
-  # wait till CRD db2uclusters.db2u.databases.ibm.com NamesAccepted=True STARTS  
-  wait_period=0
-  while true
-  do
-    wait_period=$(($wait_period+10))
-    if [ $wait_period -gt 300 ];then
-      echo_reset_dim "${COLOR_RED}CRD db2uclusters.db2u.databases.ibm.com is not ready with in 300 sec, exiting"
-      exit 1
-    else
-      sleep 10
-    fi
-    export DB2_CRD_NAMES_ACCEPTED_STATUS=`oc get crd  db2uclusters.db2u.databases.ibm.com -o=jsonpath="{.status.conditions[?(@.type=='NamesAccepted')].status}"`
-    echo_reset_dim "DB2_CRD_NAMES_ACCEPTED_STATUS .... ${COLOR_MAGENTA}${DB2_CRD_NAMES_ACCEPTED_STATUS}"
-
-    if [[ "$DB2_CRD_NAMES_ACCEPTED_STATUS" == "True" ]]; then
-      break
-    fi
-  done  
-  # wait till CRD db2uclusters.db2u.databases.ibm.com NamesAccepted=True DONE
-}
-
-# Invoke suite_db2_setup_for_manage
-function invoke_suite_db2_setup_for_manage(){
-  # This should really be in the manage operator
-
-  echo
-  echo_h2 "Creating setupdb.sh file"
-  jinja -X .+ $CLI_DIR/templates/gitops/files/manage/setupdb.sh.j2 -o ${TEMP_DIR}/setupdb.sh
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  chmod +x ${TEMP_DIR}/setupdb.sh
-
-  echo
-  echo_h2 "Copying setupdb.sh file to ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc cp ${TEMP_DIR}/setupdb.sh ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0:/tmp/setupdb.sh -c db2u
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  echo
-  echo_h2 "Executing setupdb.sh file on ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc '/tmp/setupdb.sh | tee /tmp/setupdb.log' db2inst1
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  echo
-  echo_h2 "Creating /mnt/backup/MIRRORLOGPATH in c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0  -- su -lc "mkdir -p /mnt/backup/MIRRORLOGPATH" db2inst1
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  echo
-  echo_h2 "Creating /mnt/bludata0/db2/archive_log in c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0  -- su -lc "mkdir -p /mnt/bludata0/db2/archive_log/" db2inst1
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  echo
-  echo_h2 "Creating /mnt/backup/staging in c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0  -- su -lc "mkdir -p /mnt/backup/staging" db2inst1
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-}
-
-# Invoke the DB2 backup when needed
-invoke_suite_db2_backup() {
-  echo
-  echo_h2 "Creating backupdb.sh file"
-  jinja -X .+ $CLI_DIR/templates/gitops/files/manage/backupdb.sh.j2 -o ${TEMP_DIR}/backupdb.sh
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  chmod +x ${TEMP_DIR}/backupdb.sh
-
-  echo
-  echo_h2 "Copying backupdb.sh file to ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc cp ${TEMP_DIR}/backupdb.sh ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0:/tmp/backupdb.sh -c db2u
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-
-  echo
-  echo_h2 "Executing backupdb.sh file on ${DB2_NAMESPACE}/c-${DB2_INSTANCE_NAME}-db2u-0"
-  oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc '/tmp/backupdb.sh | tee /tmp/backupdb.log' db2inst1
-  rc=$?
-  [ $rc -ne 0 ] && exit $rc
-}
-
 function gitops_db2u_database() {
   # Take the first parameter off (it will be create-gitops)
   shift
@@ -372,8 +298,7 @@ function gitops_db2u_database() {
 
   mkdir -p ${GITOPS_WORKING_DIR}
   rm -rf $GITOPS_WORKING_DIR/$GITHUB_REPO
-  GITOPS_CLUSTER_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${CLUSTER_ID}
-  GITOPS_APPS_DIR=${GITOPS_CLUSTER_DIR}/apps
+  GITOPS_INSTANCE_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${ACCOUNT_ID}/${REGION}/${CLUSTER_ID}/${MAS_INSTANCE_ID}/db2-databases
 
   #Defaults
   if [[ -z $DB2_DBNAME ]]; then
@@ -453,12 +378,6 @@ DB2_WORKLOAD: '${DB2_WORKLOAD}'"
 
   # by default db2 internal is true, set it to false if db2 is external
   export DB2_INTERNAL=${DB2_INTERNAL:-"true"}
-  export WHOAMI=`oc whoami`
-  if [[ -z ${WHOAMI} ]]; then
-    echo_reset_dim "${COLOR_RED} Please do 'oc login' to the cluster ArgoCD is to be installed on"
-    exit 1
-  fi
-  export CLUSTER_DOMAIN=`oc get ingress.config.openshift.io  cluster -o=jsonpath='{.spec.domain}'`
 
   echo
   reset_colors
@@ -467,8 +386,9 @@ DB2_WORKLOAD: '${DB2_WORKLOAD}'"
   echo "${TEXT_DIM}"
   echo_h2 "Target" "    "
   echo_reset_dim "Account ID ............................ ${COLOR_MAGENTA}${ACCOUNT_ID}"
+  echo_reset_dim "Region ................................ ${COLOR_MAGENTA}${REGION}"
   echo_reset_dim "Cluster ID ............................ ${COLOR_MAGENTA}${CLUSTER_ID}"
-  echo_reset_dim "Application Directory ................. ${COLOR_MAGENTA}${GITOPS_APPS_DIR}"
+  echo_reset_dim "Instance Config Directory ............. ${COLOR_MAGENTA}${GITOPS_INSTANCE_DIR}"
   reset_colors
 
   echo "${TEXT_DIM}"
@@ -534,7 +454,6 @@ DB2_WORKLOAD: '${DB2_WORKLOAD}'"
   echo_reset_dim "db2-cpu-limits  ......................... ${COLOR_MAGENTA}${DB2_CPU_LIMITS}"
   echo_reset_dim "db2-memory-requests  .................... ${COLOR_MAGENTA}${DB2_MEMORY_REQUESTS}"
   echo_reset_dim "db2-memory-limits  ...................... ${COLOR_MAGENTA}${DB2_MEMORY_LIMITS}"
-  echo_reset_dim "cluster_domain .......................... ${COLOR_MAGENTA}${CLUSTER_DOMAIN}"
   echo_reset_dim "db2-instance-registry-yaml .............. ${COLOR_MAGENTA}${DB2_INSTANCE_REGISTRY_YAML}"
   echo_reset_dim "db2-instance-dbm-config-yaml ............ ${COLOR_MAGENTA}${DB2_INSTANCE_DBM_CONFIG_YAML}"
   echo_reset_dim "db2-database-db-config-yaml ............. ${COLOR_MAGENTA}${DB2_DATABASE_DB_CONFIG_YAML}"
@@ -542,6 +461,21 @@ DB2_WORKLOAD: '${DB2_WORKLOAD}'"
 
   AVP_TYPE=aws  # Support for IBM will be added later
   sm_login
+
+
+  # Set by postsync job in redhat-cert-manager chart
+  # This is a workaround for the fact that we cannot interact with the cluster directly (see https://jsw.ibm.com/browse/MASCORE-1425)
+  # NOTE: this isn't a secret value, so it's safe to fetch it here and embed it in our config in the clear
+  echo "Fetching cluster domain from Secrets manager"
+  export CLUSTER_DOMAIN=`oc get ingress.config.openshift.io  cluster -o=jsonpath='{.spec.domain}'`
+  export SECRET_NAME_CLUSTER_DOMAIN=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}cluster_domain
+  export CLUSTER_DOMAIN=$(sm_get_secret_value ${SECRET_NAME_CLUSTER_DOMAIN} "cluster_domain")
+  echo "cluster domain: ${CLUSTER_DOMAIN}"
+  if [[ -z "${CLUSTER_DOMAIN}" ]]; then
+    echo "Failed to fetch cluster domain from secrets manager"
+    exit
+  fi
+
 
   CURRENT_DIR=$PWD
   TEMP_DIR=$CURRENT_DIR/tmp-db2u-database
@@ -575,74 +509,59 @@ DB2_WORKLOAD: '${DB2_WORKLOAD}'"
     echo_h2 "Cloning GitHub repo $GITHUB_ORG $GITHUB_REPO"
     clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_WORKING_DIR $GIT_SSH
   fi
-  mkdir -p ${GITOPS_APPS_DIR}
+  mkdir -p ${GITOPS_INSTANCE_DIR}
 
   # wait till CRD db2uclusters.db2u.databases.ibm.com NamesAccepted=True 
-  wait_for_db2ucluster_crd
+  # This is now performed as a presync hook in the ibm-db2u-database chart
+  # as a workaround for the fact that we can no longer directly call the cluster
+  # See: https://jsw.ibm.com/browse/MASCORE-1425
+  # wait_for_db2ucluster_crd
 
   GITOPS_TMP_DIR=${GITOPS_CLUSTER_DIR}/tmp
   mkdir -p ${GITOPS_TMP_DIR}
-
-  export DB2CFG_SETTINGS_APPLIED_FILE=${GITOPS_TMP_DIR}/db2cfg-settings-applied.json
-  export DB2CFG_SETTINGS_APPLIED_SECRET=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}${MAS_APP_ID}${SECRETS_KEY_SEPERATOR}db2cfg
-  sm_get_secret_file ${DB2CFG_SETTINGS_APPLIED_SECRET} ${DB2CFG_SETTINGS_APPLIED_FILE}
-
-  export DB2CFG_SETTINGS_APPLIED=$(jq -r .'db2cfg_settings_applied' ${DB2CFG_SETTINGS_APPLIED_FILE})
-  echo "DB2CFG_SETTINGS_APPLIED=${DB2CFG_SETTINGS_APPLIED}"
-  if [[ "${DB2CFG_SETTINGS_APPLIED}" != "true" ]]; then
-    echo_h2 "setting DB2CFG_SETTINGS_APPLIED to false "
-    export DB2CFG_SETTINGS_APPLIED="false"
-  fi
 
   # Generate ArgoApps
   # ---------------------------------------------------------------------------
   echo
   echo_h2 "Generating DB2U Database Configuraton"
   echo
-  echo_reset_dim "- Generating DB2U Database file ${GITOPS_APPS_DIR}/${MAS_INSTANCE_ID}.${MAS_APP_ID}.ibm-db2u-database.yaml"
-  jinja -X .+ $CLI_DIR/templates/gitops/ibm-db2u-database.yaml.j2 -o ${GITOPS_APPS_DIR}/${MAS_INSTANCE_ID}.${MAS_APP_ID}.ibm-db2u-database.yaml
+  GENERATED_CONFIG_FILE="${GITOPS_INSTANCE_DIR}/${DB2_INSTANCE_NAME}.ibm-db2u-database.yaml"
+  echo_reset_dim "- Generating DB2U Database file ${GENERATED_CONFIG_FILE}"
+  jinja -X .+ $CLI_DIR/templates/gitops/appset-configs/cluster/instance/db2-databases/ibm-db2u-database.yaml.j2 -o ${GENERATED_CONFIG_FILE}
 
   # Commit and push to github target repo
   # ---------------------------------------------------------------------------
   if [ "$GITHUB_PUSH" == "true" ]; then
     echo
     echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
-    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_APPS_DIR "${GIT_COMMIT_MSG}"
+    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"
     echo "git: Added ${FILES_ADDED} files"
+
+    # The DB2CFG_SETTINGS_APPLIED secret is read by the postsync hook in the ibm-db2u-database chart
+    # Since we have made changes to the db2u-database config here, we want the postsync hook to rerun,
+    # so set the secret to false
     if [[ "$FILES_ADDED" != "0" ]]; then
-      echo_h2 "setting DB2CFG_SETTINGS_APPLIED to false"
+      echo_h2 "setting DB2CFG_SETTINGS_APPLIED to false to prompt postsync hooks to run"
       export DB2CFG_SETTINGS_APPLIED="false"
+      export DB2CFG_SETTINGS_APPLIED_SECRET=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}db2${SECRETS_KEY_SEPERATOR}${DB2_INSTANCE_NAME}/settings_applied
+      sm_update_secret ${DB2CFG_SETTINGS_APPLIED_SECRET} "{ \"db2cfg_settings_applied\": \"${DB2CFG_SETTINGS_APPLIED}\" }"
+      rc=$?
+      [ $rc -ne 0 ] && exit $rc
     fi
+
+    INSTANCE_ROOT_APP="instance.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
+    DB2_DATABASE_APP="db2-db.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}.${MAS_APP_ID}"
+
     argocd_login
-    argocd_sync ${CLUSTER_ID}-watcher
-    argocd_hard_refresh mas-${MAS_INSTANCE_ID}-${MAS_APP_ID}-db2-database
-    check_argo_app_synced mas-${MAS_INSTANCE_ID}-${MAS_APP_ID}-db2-database ${CLUSTER_ID}-watcher ${DB2_NAMESPACE}
-    check_argo_app_healthy mas-${MAS_INSTANCE_ID}-${MAS_APP_ID}-db2-database ${CLUSTER_ID}-watcher
-  fi
-  echo "DB2CFG_SETTINGS_APPLIED= ${DB2CFG_SETTINGS_APPLIED} FILES_ADDED= ${FILES_ADDED} DB2_INTERNAL=${DB2_INTERNAL} MAS_APP_ID=${MAS_APP_ID}"  
-  # Run specific setupcmds for Manage only if we have made changes.
-  if [[ "$DB2_INTERNAL" == "true" && "${DB2CFG_SETTINGS_APPLIED}" != "true" && "$MAS_APP_ID" == "manage" ]]; then
-    invoke_suite_db2_setup_for_manage 
-  fi
+    argocd_sync "${INSTANCE_ROOT_APP}" ## trigger the db2-db appset to pick up the new config files
+    check_argo_app_synced "${INSTANCE_ROOT_APP}" "${CLUSTER_ROOT_APP}" # wait for the instance root app to sync
 
-  # Run DB2 apply script if we have made any changes.
-  if [[ "$DB2_INTERNAL" == "true" && "${DB2CFG_SETTINGS_APPLIED}" != "true" ]]; then
-    echo
-    echo_h2 "Calling apply-db2cfg-settings.sh file on c-${DB2_INSTANCE_NAME}-db2u-0"
-    oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc '/db2u/scripts/apply-db2cfg-settings.sh --setting all | tee /tmp/apply-db2cfg-settings.log' db2inst1
-    rc=$?
-    [ $rc -ne 0 ] && exit $rc
-    # Some parameters like LOGARCHMETH1 being set can cause a backup to be needed as it moves
-    # to archival logging. Do that backup now if we are in that state. The function checks that
-    # SQL1116N is being return from connect, and does nothin otherwise
-    invoke_suite_db2_backup
+    argocd_hard_refresh "${DB2_DATABASE_APP}"
+    check_argo_app_synced "${DB2_DATABASE_APP}" "${INSTANCE_ROOT_APP}"
+    check_argo_app_healthy "${DB2_DATABASE_APP}" "${INSTANCE_ROOT_APP}"
 
-    echo "sm_update_secret ...DB2CFG_SETTINGS_APPLIED with true"
-    export DB2CFG_SETTINGS_APPLIED="true"
-    sm_update_secret ${DB2CFG_SETTINGS_APPLIED_SECRET} "{ \"db2cfg_settings_applied\": \"${DB2CFG_SETTINGS_APPLIED}\" }"
-    rc=$?
-    [ $rc -ne 0 ] && exit $rc
   fi
+  
   if [ "$GITHUB_PUSH" == "true" ]; then
 	  remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO
   fi
diff --git a/image/cli/mascli/functions/gitops_deprovision_suite b/image/cli/mascli/functions/gitops_deprovision_suite
--- a/image/cli/mascli/functions/gitops_deprovision_suite
+++ b/image/cli/mascli/functions/gitops_deprovision_suite
@@ -13,12 +13,16 @@ GitOps Configuration:
   -d, --dir ${COLOR_YELLOW}GITOPS_WORKING_DIR${TEXT_RESET}           Directory for GitOps repository
   -g, --gitops-version ${COLOR_YELLOW}GITOPS_VERSION${TEXT_RESET}    Version of ibm-mas/gitops to use
   -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}            Account name that the cluster belongs to
+  -r, --region-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}             Region ID
   -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}            Cluster ID
   -m, --mas-instance-id ${COLOR_YELLOW}MAS_INSTANCE_ID${TEXT_RESET}  IBM Suite Maximo Application Suite Instance ID
   -f, --force-removal ${COLOR_YELLOW}FORCE_REMOVAL${TEXT_RESET}      Force remove the ArgoCD Application, when deletion exceeds timeout
 
 MongoDb Provider Selection:
       --mongo-provider ${COLOR_YELLOW}MONGODB_PROVIDER${TEXT_RESET}  The mongodb provider to install. Only "aws" is supported
+
+AWS MongoDb Provider:
+      --user-action ${COLOR_YELLOW}USER_ACTION${TEXT_RESET}          The action to take, add or remove user
 
 Secrets Manager:
       --secrets-path ${COLOR_YELLOW}SECRETS_PATH${TEXT_RESET}                    Secrets Manager path
@@ -55,6 +59,8 @@ function gitops_deprovision_suite_noninteractive() {
   GIT_COMMIT_MSG="gitops-deprovision-suite commit"
   export GITOPS_VERSION=${GITOPS_VERSION:-poc}
 
+  export REGION=${REGION:-${SM_AWS_REGION}}
+
   while [[ $# -gt 0 ]]
   do
     key="$1"
@@ -69,6 +75,9 @@ function gitops_deprovision_suite_noninteractive() {
         ;;
       -a|--account-id)
         export ACCOUNT_ID=$1 && shift
+        ;;
+      -r|--region-id)
+        export REGION=$1 && shift
         ;;
       -c|--cluster-id)
         export CLUSTER_ID=$1 && shift
@@ -90,6 +99,11 @@ function gitops_deprovision_suite_noninteractive() {
       # MongoDb Provider Selection
       --mongo-provider)
         export MONGODB_PROVIDER=$1 && shift
+        ;;
+
+      # AWS MongoDb provider
+      --user-action)
+        export USER_ACTION=$1 && shift
         ;;
 
       # SLS
@@ -150,7 +164,17 @@ function gitops_deprovision_suite_noninteractive() {
   done
 
   [[ -z "$ACCOUNT_ID" ]] && gitops_deprovision_suite_help "ACCOUNT_ID is not set"
+  [[ -z "$REGION" ]] && gitops_deprovision_app_config_help "REGION is not set"
   [[ -z "$CLUSTER_ID" ]] && gitops_deprovision_suite_help "CLUSTER_ID is not set"
+  [[ -z "$MONGODB_PROVIDER" ]] && gitops_deprovision_suite_help "MONGODB_PROVIDER is not set"
+  if [ $MONGODB_PROVIDER == 'aws' ]; then
+    [[ -z "$USER_ACTION" ]] && gitops_deprovision_suite_help "USER_ACTION is not set"
+    [[ -z "$MAS_INSTANCE_ID" ]] && gitops_deprovision_suite_help "MAS_INSTANCE_ID is not set"
+    if [ -z $SM_AWS_ACCESS_KEY_ID ] || [ -z $SM_AWS_SECRET_ACCESS_KEY ] || [ -z $SM_AWS_REGION ]; then
+      echo 'Missing required params for AWS mongo provider, make sure to provide --aws-access-key, --aws-secret-key, --aws-region'
+      exit 1
+    fi
+  fi
 
   if [[ "$GITHUB_PUSH" == "true" ]]; then
     [[ -z "$GITHUB_HOST" ]] && gitops_deprovision_suite_help "GITHUB_HOST is not set"
@@ -173,8 +197,7 @@ function gitops_deprovision_suite() {
   fi
 
   mkdir -p ${GITOPS_WORKING_DIR}
-  GITOPS_CLUSTER_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${CLUSTER_ID}
-  GITOPS_APPS_DIR=${GITOPS_CLUSTER_DIR}/apps
+  GITOPS_INSTANCE_DIR=${GITOPS_WORKING_DIR}/${GITHUB_REPO}/${ACCOUNT_ID}/${REGION}/${CLUSTER_ID}/${MAS_INSTANCE_ID}
 
   echo
   reset_colors
@@ -183,8 +206,9 @@ function gitops_deprovision_suite() {
   echo "${TEXT_DIM}"
   echo_h2 "Target" "    "
   echo_reset_dim "Account ID ............................ ${COLOR_MAGENTA}${ACCOUNT_ID}"
+  echo_reset_dim "Region ID ............................. ${COLOR_MAGENTA}${REGION}"
   echo_reset_dim "Cluster ID ............................ ${COLOR_MAGENTA}${CLUSTER_ID}"
-  echo_reset_dim "Application Directory ................. ${COLOR_MAGENTA}${GITOPS_APPS_DIR}"
+  echo_reset_dim "Application Directory ................. ${COLOR_MAGENTA}${GITOPS_INSTANCE_DIR}"
   echo_reset_dim "Force Remove Application Flag ......... ${COLOR_MAGENTA}${FORCE_REMOVAL}"
   reset_colors
 
@@ -196,6 +220,12 @@ function gitops_deprovision_suite() {
   echo "${TEXT_DIM}"
   echo_h2 "Mongo" "    "
   echo_reset_dim "Mongo Provider  ....................... ${COLOR_MAGENTA}${MONGODB_PROVIDER}"
+  if [ $MONGODB_PROVIDER == 'aws' ]; then
+    echo_reset_dim "User Action  .......................... ${COLOR_MAGENTA}${USER_ACTION}"
+    echo_reset_dim "AWS Access Key ID  .................... ${COLOR_MAGENTA}${SM_AWS_ACCESS_KEY_ID:0:4}<snip>"
+    echo_reset_dim "AWS Secret Access Key  ................ ${COLOR_MAGENTA}${SM_AWS_SECRET_ACCESS_KEY:0:8}<snip>"
+    echo_reset_dim "AWS Region  ........................... ${COLOR_MAGENTA}${SM_AWS_REGION}"
+  fi
   reset_colors
 
   echo "${TEXT_DIM}"
@@ -221,18 +251,8 @@ function gitops_deprovision_suite() {
   reset_colors
 
   echo "${TEXT_DIM}"
-  echo_h2 "IBM Suite License Service" "    "
-  echo_reset_dim "Subscription Channel .................. ${COLOR_MAGENTA}${SLS_CHANNEL}"
-  reset_colors
-
-  echo "${TEXT_DIM}"
   echo_h2 "IBM Maximo Application Suite" "    "
   echo_reset_dim "Instance ID ........................... ${COLOR_MAGENTA}${MAS_INSTANCE_ID}"
-  echo_reset_dim "Subscription Channel .................. ${COLOR_MAGENTA}${MAS_CHANNEL}"
-  echo_reset_dim "Domain ................................ ${COLOR_MAGENTA}${MAS_DOMAIN}"
-  echo_reset_dim "Image Tags ............................ ${COLOR_MAGENTA}${MAS_IMAGE_TAGS}"
-  echo_reset_dim "Annotations ........................... ${COLOR_MAGENTA}${MAS_ANNOTATIONS}"
-  echo_reset_dim "Labels ................................ ${COLOR_MAGENTA}${MAS_LABELS}"
   reset_colors
 
 
@@ -243,21 +263,69 @@ function gitops_deprovision_suite() {
   AVP_TYPE=aws  # Support for IBM will be added later
   sm_login
 
+  # Define cluster-level secrets used
+  # ---------------------------------------------------------------------------  
+  export SECRET_NAME_AWS_ACCESS=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}aws
+  export SECRET_KEY_AWS_ACCESS_KEY_ID=${SECRET_NAME_AWS_ACCESS}#sm_aws_access_key_id
+  export SECRET_KEY_AWS_SECRET_ACCESS_KEY=${SECRET_NAME_AWS_ACCESS}#sm_aws_secret_access_key
+  # The AWS secret is established by the gitops_cluster step
+  # Get the cluster-level secrets used
+  # ---------------------------------------------------------------------------
+  # Note that this cluster-level secret is set up by gitops-mongo
+  export SECRET_NAME_MASTER_MONGO=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}mongo
+  export SECRET_KEY_DOCDB_HOST=${SECRET_NAME_MASTER_MONGO}#docdb_host
+  export SECRET_KEY_DOCDB_PORT=${SECRET_NAME_MASTER_MONGO}#docdb_port
+  export SECRET_KEY_DOCDB_MASTER_USERNAME=${SECRET_NAME_MASTER_MONGO}#username
+  export SECRET_KEY_DOCDB_MASTER_PASSWORD=${SECRET_NAME_MASTER_MONGO}#password
+  export SECRET_KEY_DOCDB_MASTER_INFO=${SECRET_NAME_MASTER_MONGO}#info
+
   CURRENT_DIR=$PWD
   TEMP_DIR=$CURRENT_DIR/tmp-suite-deprovision
-  rm -rf TEMP_DIR
+  rm -rf $TEMP_DIR
   mkdir -p $TEMP_DIR
+
+  # by default yaml. pass aws, in case if configuring with DocDB
+  export MONGODB_PROVIDER=${MONGODB_PROVIDER:-"yaml"}
+
+  export MONGO_SECRET_FILE=$TEMP_DIR/mongo-secret.json
+  export MONGO_CONFIG_FILE=$TEMP_DIR/mongo-info.yaml
+  
+  sm_get_secret_file ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}mongo $MONGO_SECRET_FILE
+
+  jq -r .info $MONGO_SECRET_FILE > $MONGO_CONFIG_FILE
+  UNESCAPED_MONGO_INFO=$(jq -r .info $MONGO_SECRET_FILE)
+
+  # Instance-level secrets to create (as its referenced in ibm-sls.yaml.j2 template). 
+  # ---------------------------------------------------------------------------
+  export SECRET_NAME_MONGO=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}mongo
+  export SECRET_KEY_MONGO_USERNAME=${SECRET_NAME_MONGO}#username
+  export SECRET_KEY_MONGO_PASSWORD=${SECRET_NAME_MONGO}#password
+  export SECRET_KEY_MONGO_INFO=${SECRET_NAME_MONGO}#info
+  
+  export MONGO_INSTANCE_SECRET_FILE=$TEMP_DIR/mongo-instance-secret.json
+  sm_get_secret_file ${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}mongo $MONGO_INSTANCE_SECRET_FILE
+  INSTANCE_MONGO_USERNAME=$(jq -r .username $MONGO_INSTANCE_SECRET_FILE)
+  INSTANCE_MONGO_PASSWORD=$(jq -r .password $MONGO_INSTANCE_SECRET_FILE)
+
+  # Please note mongo instance secret will be deleted in gitops helm template via PostSync job. 
+  # We are temporarily creating it, as the same is reference in ibm-sls.yaml.j2 template
+
+  ESCAPED_INFO=${UNESCAPED_MONGO_INFO//\"/\\\"}
+  ESCAPED_INFO=${ESCAPED_INFO//$'\n'/\\n}
+  sm_update_secret $SECRET_NAME_MONGO "{\"info\": \"$ESCAPED_INFO\", \"username\": \"$INSTANCE_MONGO_USERNAME\", \"password\": \"$INSTANCE_MONGO_PASSWORD\"}"
+
 
   # Instance-level secrets to delete
   # ---------------------------------------------------------------------------
-  export SECRET_NAME_MONGO=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}mongo
+  # export SECRET_NAME_MONGO=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}mongo
   export SECRET_NAME_LICENSE_FILE=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}license
   export PUBLIC_CERT_SECRET_NAME=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}certs${SECRETS_KEY_SEPERATOR}core
 
   # Delete Mongo details for this MAS Instance
   # ---------------------------------------------------------------------------
-  echo " Deleting $SECRET_NAME_MONGO"
-  sm_delete_secret $SECRET_NAME_MONGO
+  # Deleting SECRET_NAME_MONGO will happen in gitops helm template PostSync job
+  # echo " Deleting $SECRET_NAME_MONGO"
+  # sm_delete_secret $SECRET_NAME_MONGO
 
   # Delete SLS Entitlement License details for this MAS Instance
   # ---------------------------------------------------------------------------
@@ -281,52 +349,62 @@ function gitops_deprovision_suite() {
     echo_h2 "Cloning GitHub repo $GITHUB_ORG $GITHUB_REPO"
     clone_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_WORKING_DIR $GIT_SSH
   fi
-  mkdir -p ${GITOPS_APPS_DIR}
+  mkdir -p ${GITOPS_INSTANCE_DIR}
 
 
-  # Delete ArgoApps
+  # Delete Application config
   # ---------------------------------------------------------------------------
   echo
-  echo_h2 "Deleting Applications"
-  echo "- IBM Suite License Service"
-  rm ${GITOPS_APPS_DIR}/${MAS_INSTANCE_ID}.ibm-sls.yaml
+  echo_h2 "Deleting application configuration files"
+  CLUSTER_ROOT_APP="cluster.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}"
+  INSTANCE_ROOT_APP="instance.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
+  SUITE_APP_NAME="suite.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
+  SLS_APP_NAME="sls.${ACCOUNT_ID}.${REGION}.${CLUSTER_ID}.${MAS_INSTANCE_ID}"
 
-  echo "- IBM Maximo Application Suite Core Platform"
-  rm ${GITOPS_APPS_DIR}/${MAS_INSTANCE_ID}.ibm-mas-core-suite.yaml
-
-  # Commit and push to github target repo
-  # ---------------------------------------------------------------------------
   if [ "$GITHUB_PUSH" == "true" ]; then
-    echo
-    echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
-    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_APPS_DIR "${GIT_COMMIT_MSG}"
-
     argocd_login
-    argocd_sync ${CLUSTER_ID}-watcher
-
-    argocd_prune_sync ${CLUSTER_ID}-watcher
-    check_argo_app_deleted mas-${MAS_INSTANCE_ID}-sls ${MAS_INSTANCE_ID} ${FORCE_REMOVAL}
-    check_argo_app_deleted mas-${MAS_INSTANCE_ID}-core-suite ${MAS_INSTANCE_ID} ${FORCE_REMOVAL}
   fi
 
-  # Deleting AppProject after other apps have been removed
-  # ---------------------------------------------------------------------------
-  echo
-  echo_h2 "Deleting Argo Project for ${MAS_INSTANCE_ID}"
-  echo "- Project"
-  rm ${GITOPS_APPS_DIR}/${MAS_INSTANCE_ID}.appproject.yaml
+  # We'll do these one at a time so we can verify that each app disappears from ArgoCD as we go along
 
-    # Commit and push to github target repo
-  # ---------------------------------------------------------------------------
+  echo
+  echo "- Delete MAS Suite"
+  rm ${GITOPS_INSTANCE_DIR}/ibm-mas-suite.yaml
   if [ "$GITHUB_PUSH" == "true" ]; then
     echo
     echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
-    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_APPS_DIR "${GIT_COMMIT_MSG}"
+    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"
+    argocd_prune_sync "${INSTANCE_ROOT_APP}" # trigger the instance root app to notice the deletion of the config file
+    # The Suite app generated by the instance root app should disappear
+    check_argo_app_deleted ${SUITE_APP_NAME} "mas"
+  fi
+
+  echo
+  echo "- Delete SLS"
+  rm ${GITOPS_INSTANCE_DIR}/ibm-sls.yaml
+  if [ "$GITHUB_PUSH" == "true" ]; then
+    echo
+    echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
+    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"
+    argocd_prune_sync "${INSTANCE_ROOT_APP}" # trigger the instance root app to notice the deletion of the config file
+    # The SLS app generated by the instance root app should disappear
+    check_argo_app_deleted ${SLS_APP_NAME} "mas"
+  fi
+
+  echo
+  echo "- Delete base MAS instance config"
+  rm ${GITOPS_INSTANCE_DIR}/ibm-mas-instance-base.yaml
+  if [ "$GITHUB_PUSH" == "true" ]; then
+    echo
+    echo_h2 "Commit and push changes to GitHub repo $GITHUB_ORG $GITHUB_REPO"
+    save_to_target_git_repo $GITHUB_HOST $GITHUB_ORG $GITHUB_REPO $GIT_BRANCH $GITOPS_INSTANCE_DIR "${GIT_COMMIT_MSG}"
+    argocd_prune_sync "${CLUSTER_ROOT_APP}" # trigger the cluster root app to notice the deletion of the config file
+    # The instance root app should disappear
+    check_argo_app_deleted ${INSTANCE_ROOT_APP} "mas"
+  fi
+
+  if [ "$GITHUB_PUSH" == "true" ]; then
     remove_git_repo_clone $GITOPS_WORKING_DIR/$GITHUB_REPO
-
-    argocd_login
-    argocd_sync ${CLUSTER_ID}-watcher
-
-    argocd_prune_sync ${CLUSTER_ID}-watcher
   fi
+
 }
diff --git a/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2 b/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2
--- a/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2
@@ -17,11 +17,19 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
+    - name: avp_aws_secret_region
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-cis-compliance
     env:
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
       - name: ACCOUNT
@@ -34,8 +42,16 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
+      - name: SM_AWS_REGION
+        value: $(params.avp_aws_secret_region)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -44,22 +60,44 @@ spec:
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed"
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
         
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
 
-        export ARGOCD_URL=$(oc get route  openshift-gitops-server -n openshift-gitops -ojsonpath='{.spec.host}' --context $K8S_AUTH_CONTEXT)
-        export ARGOCD_USERNAME=admin
-        export ARGOCD_PASSWORD=$(oc get secret openshift-gitops-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' --context $K8S_AUTH_CONTEXT | base64 -d ; echo)
+        if [ -z $ARGOCD_URL ] || [ -z $ARGOCD_USERNAME ] || [ -z $ARGOCD_PASSWORD ]; then
+          export ARGOCD_URL=$(oc get route  openshift-gitops-server -n openshift-gitops -ojsonpath='{.spec.host}' --context $K8S_AUTH_CONTEXT)
+          export ARGOCD_USERNAME=admin
+          export ARGOCD_PASSWORD=$(oc get secret openshift-gitops-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' --context $K8S_AUTH_CONTEXT | base64 -d ; echo)
+        fi
 
         mkdir -p /tmp/init-cis-compliance
         mas gitops-cis-compliance -a $ACCOUNT -c $CLUSTER_NAME \
@@ -74,6 +112,6 @@ spec:
         - -c
       name: gitops-cis-compliance
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
diff --git a/tekton/src/tasks/gitops/gitops-cluster.yml.j2 b/tekton/src/tasks/gitops/gitops-cluster.yml.j2
--- a/tekton/src/tasks/gitops/gitops-cluster.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-cluster.yml.j2
@@ -9,10 +9,7 @@ spec:
       type: string
     - name: account
       type: string
-    - name: rosa_token
-      type: string
-      default: ""
-    - name: rosa_cluster_admin_password
+    - name: cluster_url
       type: string
       default: ""
     - name: secrets_path
@@ -25,22 +22,8 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
-      type: string
     - name: git_commit_msg
       type: string
-    - name: artifactory_username
-      type: string
-      default: ""
-    - name: artifactory_token
-      type: string
-      default: ""
-    - name: icr_username
-      type: string
-      default: ""
-    - name: icr_password
-      type: string
-      default: ""
     - name: mas_catalog_version
       type: string
       default: ""
@@ -50,10 +33,6 @@ spec:
     - name: common_services_channel
       type: string
       default: ""
-    - name: avp_aws_access_key
-      type: string
-    - name: avp_aws_secret_key
-      type: string
     - name: avp_aws_secret_region
       type: string
     - name: mas_catalog_action
@@ -62,6 +41,9 @@ spec:
     - name: common_services_action
       type: string
       default: "install"
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-cluster
     env:
@@ -69,10 +51,8 @@ spec:
         value: $(params.cluster_name)
       - name: ACCOUNT
         value: $(params.account)
-      - name: ROSA_TOKEN
-        value: $(params.rosa_token)
-      - name: ROSA_CLUSTER_ADMIN_PASSWORD
-        value: $(params.rosa_cluster_admin_password)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: SECRET_PATH
         value: $(params.secrets_path)
       - name: GIT_BRANCH
@@ -85,32 +65,28 @@ spec:
         value: $(params.github_repo)
       - name: GIT_COMMIT_MSG
         value: $(params.git_commit_msg)
-      - name: ARTIFACTORY_USERNAME
-        value: $(params.artifactory_username)
-      - name: ARTIFACTORY_TOKEN
-        value: $(params.artifactory_token)
-      - name: ICR_USERNAME
-        value: $(params.icr_username)
-      - name: ICR_PASSWORD
-        value: $(params.icr_password)
       - name: MAS_CATALOG_VERSION
         value: $(params.mas_catalog_version)
       - name: MAS_CATALOG_IMAGE
         value: $(params.mas_catalog_image)
       - name: COMMON_SERVICES_CHANNEL
         value: $(params.common_services_channel)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
       - name: MAS_CATALOG_ACTION
         value: $(params.mas_catalog_action)
       - name: COMMON_SERVICES_ACTION
         value: $(params.common_services_action)
+      - name: SM_AWS_REGION
+        value: $(params.avp_aws_secret_region)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -129,6 +105,13 @@ spec:
             echo "oc login failed"
             exit 1
           fi
+        elif [ -n $OCP_SERVER ]; then
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         else
           aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
@@ -141,7 +124,6 @@ spec:
             exit 1
           fi
         fi
-        
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
 
@@ -165,6 +147,6 @@ spec:
         - -c
       name: gitops-cluster
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
diff --git a/tekton/src/tasks/gitops/gitops-deprovision-cluster.yml.j2 b/tekton/src/tasks/gitops/gitops-deprovision-cluster.yml.j2
--- a/tekton/src/tasks/gitops/gitops-deprovision-cluster.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-deprovision-cluster.yml.j2
@@ -9,6 +9,9 @@ spec:
       type: string
     - name: account
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
     - name: secrets_path
       type: string
     - name: git_branch
@@ -19,14 +22,13 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
-      type: string
-    - name: avp_aws_access_key
-      type: string
-    - name: avp_aws_secret_key
+    - name: git_commit_msg
       type: string
     - name: avp_aws_secret_region
       type: string
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-deprovision-cluster
     env:
@@ -34,6 +36,8 @@ spec:
         value: $(params.cluster_name)
       - name: ACCOUNT
         value: $(params.account)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: SECRET_PATH
         value: $(params.secrets_path)
       - name: GIT_BRANCH
@@ -44,33 +48,55 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
+      - name: GIT_COMMIT_MSG
+        value: $(params.git_commit_msg)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: GITHUB_PAT
-        value: $(params.github_pat) 
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
         git config --global user.name "MAS Automation"
-        git config --global user.email "you@example.com"
+        git config --global user.email "mas_automation@email.com"
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed so assume there is no cluster to deprovision, exiting.."
-          exit 0
+        if [ -f $ROSA_CONFIG ]; then
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed so assume there is no cluster to deprovision, exiting.."
+            exit 0
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed so assume there is no cluster to deprovision, exiting.."
+            exit 0
+          fi
+        else
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed so assume there is no cluster to deprovision, exiting.."
+            exit 0
+          fi
         fi
-
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
         
@@ -94,6 +120,6 @@ spec:
         - -c
       name: gitops-deprovision-cluster
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
diff --git a/tekton/src/tasks/gitops/gitops-mas-fvt-preparer.yml.j2 b/tekton/src/tasks/gitops/gitops-mas-fvt-preparer.yml.j2
--- a/tekton/src/tasks/gitops/gitops-mas-fvt-preparer.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-mas-fvt-preparer.yml.j2
@@ -7,24 +7,24 @@ spec:
   params:
     - name: cluster_name
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
+    - name: devops_build_number
+      type: string
     - name: pipeline_storage_class
       type: string
     - name: aws_region
-      type: string
-    - name: aws_secret_access_key
-      type: string
-    - name: aws_access_key_id
       type: string
     - name: fvt_pipeline_name
       type: string
     - name: cli_version
       type: string
-    - name: fvt_artifactory_username
-      type: string
-    - name: fvt_artifactory_token
-      type: string
     - name: fvt_config
       type: string
+    - name: argocd_url
+      type: string
+      default: ""
 
     - name: fvt_version_core
       type: string
@@ -67,24 +67,10 @@ spec:
       type: string
     - name: fvt_whitelist_core
       type: string
-    - name: ddp_apikey
-      type: string
-    - name: partium_username
-      type: string
-    - name: partium_password
-      type: string
 
     - name: artifactory_generic_release_url
       type: string
     - name: fvt_ansible_version
-      type: string
-    - name: artifactory_auth_header
-      type: string
-    - name: devops_mongo_uri
-      type: string
-    - name: devops_build_number
-      type: string
-    - name: devops_job_number
       type: string
 
     - name: fvt_image_registry
@@ -168,24 +154,22 @@ spec:
     env:
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
+      - name: TRAVIS_BUILD_NUMBER
+        value: $(params.devops_build_number)
+      - name: DEVOPS_BUILD_NUMBER
+        value: $(params.devops_build_number)
       - name: MAS_INSTANCE_ID
         value: $(params.mas_instance_id)
       - name: PIPELINE_STORAGE_CLASS
         value: $(params.pipeline_storage_class)
       - name: AWS_REGION
         value: $(params.aws_region)
-      - name: AWS_SECRET_ACCESS_KEY
-        value: $(params.aws_secret_access_key)
-      - name: AWS_ACCESS_KEY_ID
-        value: $(params.aws_access_key_id)
       - name: FVT_PIPELINE_NAME
         value: $(params.fvt_pipeline_name)
       - name: CLI_VERSION
         value: $(params.cli_version)
-      - name: FVT_ARTIFACTORY_USERNAME
-        value: $(params.fvt_artifactory_username)
-      - name: FVT_ARTIFACTORY_TOKEN
-        value: $(params.fvt_artifactory_token)
       - name: FVT_CONFIG
         value: $(params.fvt_config)
       - name: FVT_IMAGE_REGISTRY
@@ -194,24 +178,6 @@ spec:
         value: $(params.artifactory_generic_release_url)
       - name: FVT_ANSIBLE_VERSION
         value: $(params.fvt_ansible_version)
-      - name: ARTIFACTORY_AUTH_HEADER
-        value: $(params.artifactory_auth_header)
-      - name: DEVOPS_MONGO_URI
-        value: $(params.devops_mongo_uri)
-      - name: TRAVIS_BUILD_NUMBER
-        value: $(params.devops_build_number)
-      - name: TRAVIS_JOB_NUMBER
-        value: $(params.devops_job_number)
-      - name: DEVOPS_BUILD_NUMBER
-        value: $(params.devops_build_number)
-      - name: DEVOPS_JOB_NUMBER
-        value: $(params.devops_job_number)
-      - name: DDP_APIKEY
-        value: $(params.ddp_apikey)
-      - name: PARTIUM_USERNAME
-        value: $(params.partium_username)
-      - name: PARTIUM_PASSWORD
-        value: $(params.partium_password)
       - name: MAS_WORKSPACE_ID
         value: $(params.mas_workspace_id)
       - name: MAS_CHANNEL
@@ -288,33 +254,54 @@ spec:
         value: $(params.mas_app_channel_optimizer)
       - name: MAS_APP_CHANNEL_PREDICT
         value: $(params.mas_app_channel_predict)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
 
-        export ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed, exiting with error.."
-          exit 1
+        ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
+        if [ -f $ROSA_CONFIG ]; then
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
 
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
 
-        export MAS_CONFIG_DIR=/tmp/additional-configs
-        mkdir -p $MAS_CONFIG_DIR
-
-        cp -rL /workspace/shared-entitlement/. /tmp/additional-configs/
-        cp -rL /workspace/shared-additional-configs/. /tmp/additional-configs/
-        cp -rL /workspace/shared-gitops-configs/. /tmp/additional-configs/
-
         echo "Installing ibm.mas_fvt ansible collection (with retries)"
-        wget --header="$ARTIFACTORY_AUTH_HEADER" ${ARTIFACTORY_GENERIC_RELEASE_URL}/maximoappsuite/ansible-fvt/${FVT_ANSIBLE_VERSION}/ibm-mas_fvt-${FVT_ANSIBLE_VERSION}.tar.gz || exit 1
+        wget --header="Authorization:Bearer $FVT_ARTIFACTORY_TOKEN" ${ARTIFACTORY_GENERIC_RELEASE_URL}/maximoappsuite/ansible-fvt/${FVT_ANSIBLE_VERSION}/ibm-mas_fvt-${FVT_ANSIBLE_VERSION}.tar.gz || exit 1
 
         MAX_ATTEMPTS=5
         ATTEMPT=1
@@ -337,19 +324,26 @@ spec:
         fi
         echo "argo:argocd login : ARGOCD_URL=$ARGOCD_URL ARGOCD_USERNAME=$ARGOCD_USERNAME ARGOCD_PASSWORD=${ARGOCD_PASSWORD:0:8}<snip> ..."    
         argocd login $ARGOCD_URL --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
-        echo "argo:argocd proj windows add $MAS_INSTANCE_ID --kind deny --schedule * * * * * --duration 4h --applications *"  
-        argocd proj windows add $MAS_INSTANCE_ID --kind deny --schedule "* * * * *" --duration 4h --applications "*"
+        echo "argo:argocd proj windows add mas --kind deny --schedule * * * * * --duration 4h --applications *"  
+        argocd proj windows add mas --kind deny --schedule "* * * * *" --duration 4h --applications "*.$MAS_INSTANCE_ID"
 
-        mas gitops-mas-fvt-preparer --pipeline-storage-class ${PIPELINE_STORAGE_CLASS} \
-        --dir $MAS_CONFIG_DIR
+        mas gitops-mas-fvt-preparer --pipeline-storage-class ${PIPELINE_STORAGE_CLASS}
+
+        # Wait for launcher to complete
+        /opt/app-root/src/wait-for-pipelinerun.sh --name $MAS_INSTANCE_ID-fvt-launcher-$DEVOPS_BUILD_NUMBER --namespace mas-$MAS_INSTANCE_ID-pipelines
+
+        # Remove argocd window
+        echo "argo:argocd login : ARGOCD_URL=$ARGOCD_URL ARGOCD_USERNAME=$ARGOCD_USERNAME ARGOCD_PASSWORD=${ARGOCD_PASSWORD:0:8}<snip> ..."
+        argocd login $ARGOCD_URL --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
+        ARGOWINDOW=$(argocd proj windows list mas | grep "*.$MAS_INSTANCE_ID" | cut -c1-1)
+        echo "argo:argocd proj windows delete mas $ARGOWINDOW"
+        argocd proj windows delete mas $ARGOWINDOW
+
       command:
         - /bin/sh
         - -c
       name: gitops-mas-fvt-preparer
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
-    - name: shared-entitlement
-    - name: shared-additional-configs
-    - name: shared-gitops-configs
diff --git a/tekton/src/tasks/gitops/gitops-suite-config.yml.j2 b/tekton/src/tasks/gitops/gitops-suite-config.yml.j2
--- a/tekton/src/tasks/gitops/gitops-suite-config.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-suite-config.yml.j2
@@ -24,13 +24,7 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
-      type: string
     - name: avp_aws_secret_region
-      type: string
-    - name: avp_aws_secret_key
-      type: string
-    - name: avp_aws_access_key
       type: string
     - name: dro_url
       type: string
@@ -44,9 +38,17 @@ spec:
     - name: dro_ca_certificate_file
       type: string
       default: ""
+    - name: cluster_url
+      type: string
+      default: ""
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-suite-config
     env:
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
       - name: ACCOUNT
@@ -65,14 +67,10 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
+      - name: REGION_ID
+        value: $(params.avp_aws_secret_region)
       - name: DRO_URL
         value: $(params.dro_url)
       - name: DRO_CONTACT_EMAIL
@@ -83,6 +81,14 @@ spec:
         value: $(params.dro_contact_lastname)
       - name: DRO_CA_CERTIFICATE_FILE
         value: $(params.dro_ca_certificate_file)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -93,14 +99,37 @@ spec:
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed to $OCP_SERVER"
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          echo "oc login : via ROSA_CONFIG"
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed to $OCP_SERVER"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          echo "oc login : OCP_USERNAME=$OCP_USERNAME OCP_SERVER=$OCP_SERVER OCP_PASSWORD=${OCP_PASSWORD:0:8}<snip> ..."
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          echo "oc login : via ocp_login"
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
         
         echo "Set k8s context"
@@ -117,6 +146,8 @@ spec:
         fi
 
         if [ -z $DRO_CA_CERTIFICATE_FILE ]; then
+
+          # NOTE: the name of this secret is Hyperscaler specific I think? In Fyre it's called "router-certs-default".
           oc get secret $CLUSTER_NAME-primary-cert-bundle-secret -n openshift-ingress -ojsonpath='{.data.tls\.crt}' --context $K8S_AUTH_CONTEXT | base64 -d > /tmp/init-suite-config/dro_ca.crt
           export DRO_CA_CERTIFICATE_FILE=/tmp/init-suite-config/dro_ca.crt
         fi
@@ -135,7 +166,7 @@ spec:
         - -c
       name: gitops-suite-config
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
     - name: shared-additional-configs
diff --git a/tekton/src/tasks/gitops/gitops-suite-dns.yml.j2 b/tekton/src/tasks/gitops/gitops-suite-dns.yml.j2
--- a/tekton/src/tasks/gitops/gitops-suite-dns.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-suite-dns.yml.j2
@@ -30,16 +30,19 @@ spec:
       type: string
     - name: cis_crn
       type: string
-    - name: cis_apikey
-      type: string
     - name: mas_config_dir
       type: string
     - name: cis_service_name
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
 
   stepTemplate:
     name: gitops-suite-dns
     env:
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: DNS_PROVIDER
         value: $(params.dns_provider)
       - name: MAS_INSTANCE_ID
@@ -62,25 +65,54 @@ spec:
         value: $(params.cis_email)
       - name: CIS_CRN
         value: $(params.cis_crn)
-      - name: CIS_APIKEY
-        value: $(params.cis_apikey)
       - name: MAS_CONFIG_DIR
         value: $(params.mas_config_dir)
       - name: CIS_SERVICE_NAME
         value: $(params.cis_service_name)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
 
   steps:
     - args:
       - |-
+        echo "ARGOCD_URL=$ARGOCD_URL"
+        echo "CIS_APIKEY=$CIS_APIKEY"
         export ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed, exiting with error.."
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          echo "oc login : via ROSA_CONFIG"
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed, exiting with error.."
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          echo "oc login : OCP_USERNAME=$OCP_USERNAME OCP_SERVER=$OCP_SERVER OCP_PASSWORD=${OCP_PASSWORD:0:4}<snip> ..."
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          echo "oc login : via ocp_login"
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
 
         echo "Set k8s context"
@@ -96,7 +128,7 @@ spec:
         - -c
       name: gitops-suite-dns
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
 
diff --git a/tekton/src/tasks/gitops/gitops-suite.yml.j2 b/tekton/src/tasks/gitops/gitops-suite.yml.j2
--- a/tekton/src/tasks/gitops/gitops-suite.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-suite.yml.j2
@@ -19,6 +19,9 @@ spec:
     - name: mongo_provider
       type: string
       default: aws
+    - name: user_action
+      type: string
+      default: add
     - name: git_branch
       type: string
     - name: github_org
@@ -26,8 +29,6 @@ spec:
     - name: github_repo
       type: string
     - name: github_host
-      type: string
-    - name: github_pat
       type: string
     - name: sls_channel
       type: string
@@ -46,19 +47,23 @@ spec:
       type: string
     - name: avp_aws_secret_region
       type: string
-    - name: avp_aws_secret_key
-      type: string
-    - name: avp_aws_access_key
-      type: string
     - name: icr_cp
       type: string
     - name: icr_cp_open
       type: string
     - name: mas_manual_cert_mgmt
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-suite
     env:
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: DNS_PROVIDER
         value: $(params.dns_provider)
       - name: CLUSTER_NAME
@@ -69,8 +74,10 @@ spec:
         value: $(params.secrets_path)
       - name: MAS_INSTANCE_ID
         value: $(params.mas_instance_id)
-      - name: MONGO_PROVIDER
+      - name: MONGODB_PROVIDER
         value: $(params.mongo_provider)
+      - name: USER_ACTION
+        value: $(params.user_action)
       - name: GIT_BRANCH
         value: $(params.git_branch)
       - name: GITHUB_ORG
@@ -79,14 +86,8 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
       - name: MAS_DOMAIN
         value: $(params.mas_domain)
       - name: ICR_CP
@@ -105,6 +106,14 @@ spec:
         value: $(params.sls_channel)
       - name: MAS_MANUAL_CERT_MGMT
         value: $(params.mas_manual_cert_mgmt)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -114,14 +123,37 @@ spec:
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed, exiting with error.."
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          echo "oc login : via ROSA_CONFIG"
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed, exiting with error.."
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          echo "oc login : OCP_USERNAME=$OCP_USERNAME OCP_SERVER=$OCP_SERVER OCP_PASSWORD=${OCP_PASSWORD:0:4}<snip> ..."
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          echo "oc login : via ocp_login"
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
 
         echo "Set k8s context"
@@ -175,7 +207,7 @@ spec:
         - -c
       name: gitops-suite
       imagePullPolicy: IfNotPresent
-      image: quay.io/ibmmas/cli:7.10.0-pre.gitops
+      image: quay.io/ibmmas/cli:7.10.0-pre.mascore1425
   workspaces:
     - name: configs
 
