check added for sls_service value && some indentation correction
check added for sls_service value && some indentation correction

diff --git a/image/cli/mascli/functions/gitops_mas_config b/image/cli/mascli/functions/gitops_mas_config
--- a/image/cli/mascli/functions/gitops_mas_config
+++ b/image/cli/mascli/functions/gitops_mas_config
@@ -15,7 +15,7 @@ GitOps Configuration:
   -d, --dir ${COLOR_YELLOW}GITOPS_WORKING_DIR${TEXT_RESET}                     Working directory for GitOps repository
   -a, --account-id ${COLOR_YELLOW}ACCOUNT_ID${TEXT_RESET}                      Account name that the cluster belongs to
   -c, --cluster-id ${COLOR_YELLOW}CLUSTER_ID${TEXT_RESET}                      Cluster ID
-  -s ,--sls-service ${COLOR_YELLOW}STANDALONE_SLS_SERVICE${TEXT_RESET}        STANDALONE_SLS_SERVICE        
+  -s ,--sls-service ${COLOR_YELLOW}STANDALONE_SLS_SERVICE${TEXT_RESET}         SLS service parameter file Path.
   --config-action ${COLOR_YELLOW}CONFIG_ACTION${TEXT_RESET}                    One of upsert|remove.
   --mas-config-type ${COLOR_YELLOW}MAS_CONFIG_TYPE${TEXT_RESET}                One of bas|jdbc|kafka|ldap-default|mongo|objectstorage|sls|smtp
   --mas-config-scope ${COLOR_YELLOW}MAS_CONFIG-SCOPE${TEXT_RESET}              One of system|ws|app|wsapp
@@ -106,6 +106,20 @@ function gitops_mas_config_noninteractive() {
 
   export REGION_ID=${REGION_ID:-${SM_AWS_REGION}}
 
+  if [ ! -z "$STANDALONE_SLS_SERVICE" ]; then
+    CLEAN_PATH=$(echo "$STANDALONE_SLS_SERVICE" | sed 's#<ref:##; s#>##')
+    IFS='/' read -r -a PARTS <<< "$CLEAN_PATH"
+    if [ ${#PARTS[@]} -lt 6 ]; then
+        echo "Error: Invalid SLS service parameter file Path $STANDALONE_SLS_SERVICE format." >&2
+        exit 1
+    fi
+    ICN="${PARTS[3]}"
+    SAAS_SUB_ID="${PARTS[4]}"
+  fi
+  
+  export ICN=${ICN:-""}
+  export SAAS_SUB_ID=${SAAS_SUB_ID:-""}
+
   if [ -z $GIT_SSH ]; then
     export GIT_SSH="false"
   fi
@@ -160,7 +174,7 @@ function gitops_mas_config_noninteractive() {
       # SLS
       # Standalone Server configuration
       -s|--sls-service)
-        export STANDALONE_SLS_SERVICE=$1 shift
+        export STANDALONE_SLS_SERVICE=$1 && shift
       ;;
       --mas-slscfg-pod-template-yaml)
         export MAS_SLSCFG_POD_TEMPLATE_YAML=$1 && shift
@@ -587,7 +601,7 @@ function gitops_mas_config() {
       echo "${TEXT_DIM}"
       echo_reset_dim "SLS URL  ....................... ${COLOR_MAGENTA}https://sls.mas-${MAS_INSTANCE_ID}-sls.svc"
       echo_reset_dim "Pod Template YAML File  ........ ${COLOR_MAGENTA}${MAS_SLSCFG_POD_TEMPLATE_YAML}"
-      echo_reset_dim "sls service  ........ ${COLOR_MAGENTA}${STANDALONE_SLS_SERVICE}"
+      echo_reset_dim "sls service param file path .....${COLOR_MAGENTA}${STANDALONE_SLS_SERVICE}"
 
       if [[ -n "$INTERNAL_CERT_AUTHORITY" ]]; then
         echo_reset_dim "Internal Certificate Authority ...... ${COLOR_MAGENTA}${INTERNAL_CERT_AUTHORITY}"
@@ -738,16 +752,14 @@ function gitops_mas_config() {
       fi
     fi
 
-      if [ "${MAS_CONFIG_TYPE}" == "sls" ]; then
-      if [ ! -z "$STANDALONE_SLS_SERVICE" ]; then
-          CLEAN_PATH=$(echo "$STANDALONE_SLS_SERVICE" | sed 's#<ref:##; s#>##')
-          IFS='/' read -r -a PARTS <<< "$CLEAN_PATH"
-          ICN="${PARTS[3]}"
-          SAAS_SUB_ID="${PARTS[4]}"    
-        export SECRET_NAME_SLS=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${ICN}${SECRETS_KEY_SEPERATOR}${SAAS_SUB_ID}${SECRETS_KEY_SEPERATOR}sls
+    if [ "${MAS_CONFIG_TYPE}" == "sls" ]; then
+
+    if [ -z "$STANDALONE_SLS_SERVICE" ]; then
+        export SECRET_NAME_SLS="${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}sls"
       else
-        export SECRET_NAME_SLS=${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${CLUSTER_ID}${SECRETS_KEY_SEPERATOR}${MAS_INSTANCE_ID}${SECRETS_KEY_SEPERATOR}sls
-      fi
+        export SECRET_NAME_SLS="${ACCOUNT_ID}${SECRETS_KEY_SEPERATOR}${ICN}${SECRETS_KEY_SEPERATOR}${SAAS_SUB_ID}${SECRETS_KEY_SEPERATOR}sls"
+    fi
+
         
         export SECRET_KEY_SLS_URL=${SECRET_NAME_SLS}#sls_url
         export SECRET_KEY_SLS_REGISTRATION_KEY=${SECRET_NAME_SLS}#registration_key
diff --git a/image/cli/mascli/functions/gitops_suite b/image/cli/mascli/functions/gitops_suite
--- a/image/cli/mascli/functions/gitops_suite
+++ b/image/cli/mascli/functions/gitops_suite
@@ -26,7 +26,7 @@ MongoDb Provider Selection (Required):
       --mongo-provider ${COLOR_YELLOW}MONGODB_PROVIDER${TEXT_RESET}  The mongodb provider to install ('aws' or 'yaml')
 
 IBM Suite License Service:
-  -s, --sls-service ${COLOR_YELLOW}STANDALONE_SLS_SERVICE${TEXT_RESET}        STANDALONE_SLS_SERVICE        
+  -s ,--sls-service ${COLOR_YELLOW}STANDALONE_SLS_SERVICE${TEXT_RESET}         SLS service parameter file Path.
       --sls-channel ${COLOR_YELLOW}SLS_CHANNEL${TEXT_RESET}  IBM Suite License Service Subscription Channel
       --sls-install-plan ${COLOR_YELLOW}SLS_INSTALL_PLAN${TEXT_RESET}  IBM Suite License Service Subscription Install Plan ('Automatic' or 'Manual'. Default is 'Automatic')
 
@@ -139,11 +139,15 @@ function gitops_suite_noninteractive() {
   export CERT_MANAGER_NAMESPACE=${CERT_MANAGER_NAMESPACE:-"cert-manager"}
 
   if [ ! -z "$STANDALONE_SLS_SERVICE" ]; then
-        CLEAN_PATH=$(echo "$STANDALONE_SLS_SERVICE" | sed 's#<ref:##; s#>##')
-        IFS='/' read -r -a PARTS <<< "$CLEAN_PATH"
-        ICN="${PARTS[3]}"
-        SAAS_SUB_ID="${PARTS[4]}"
-  fi    
+      CLEAN_PATH=$(echo "$STANDALONE_SLS_SERVICE" | sed 's#<ref:##; s#>##')
+      IFS='/' read -r -a PARTS <<< "$CLEAN_PATH"
+      if [ ${#PARTS[@]} -lt 6 ]; then
+          echo "Error: Invalid SLS service parameter file Path $STANDALONE_SLS_SERVICE format." >&2
+          exit 1
+      fi
+      ICN="${PARTS[3]}"
+      SAAS_SUB_ID="${PARTS[4]}"
+  fi
    
   export ICN=${ICN:-""}
   export SAAS_SUB_ID=${SAAS_SUB_ID:-""}
@@ -515,8 +519,8 @@ function gitops_suite() {
   echo_h4 "IBM Suite License Service" "    "
   echo_reset_dim "Subscription Channel ........... ${COLOR_MAGENTA}${SLS_CHANNEL}"
   echo_reset_dim "Subscription Install Plan ...... ${COLOR_MAGENTA}${SLS_INSTALL_PLAN}"
-  echo_reset_dim "Ibm Customer Number  ........ ${COLOR_MAGENTA}${ICN}"
-  echo_reset_dim "Subscription Id   ........ ${COLOR_MAGENTA}${SAAS_SUB_ID}"
+  echo_reset_dim "Ibm Customer Number  ........... ${COLOR_MAGENTA}${ICN}"
+  echo_reset_dim "Subscription Id   .............. ${COLOR_MAGENTA}${SAAS_SUB_ID}"
 
 
   if [[ -n "$INTERNAL_CERT_AUTHORITY" ]]; then
