Add retry logic to save_and_unlock_target_git_repo push step (#905)

diff --git a/image/cli/mascli/functions/gitops_utils b/image/cli/mascli/functions/gitops_utils
--- a/image/cli/mascli/functions/gitops_utils
+++ b/image/cli/mascli/functions/gitops_utils
@@ -322,20 +322,26 @@ function clone_and_lock_target_git_repo() {
 
   for (( c=1; c<="${RETRIES}"; c++ )); do
     echo ""
-    echo " - clone_and_lock_git_repo: retry ${c} of ${RETRIES}"
+    echo "= clone_and_lock_git_repo: attempt ${c} of ${RETRIES}"
+    echo "================================================="
 
     # Remove any clones created by prior attempts
     rm -rf "${GITOPS_REPO_DIR}"
 
+    echo
+    echo "- clone_target_git_repo: ${GITHUB_HOST} ${GITHUB_ORG} ${GITHUB_REPO} ${GIT_BRANCH} ${LOCAL_DIR} ${SSH_PATH}"
+    echo "-------------------------------------------------"
     clone_target_git_repo "${GITHUB_HOST}" "${GITHUB_ORG}" "${GITHUB_REPO}" "${GIT_BRANCH}" "${LOCAL_DIR}" "${SSH_PATH}"
 
 
     # If the lock branch exists currently on the remote, retry after a delay
     echo
-    echo "git: ls-remote --heads origin ${GIT_LOCK_BRANCH}"
+    echo "- clone_and_lock_git_repo: ls-remote --heads origin ${GIT_LOCK_BRANCH}"
+    echo "-------------------------------------------------"
     LS_REMOTE_STDOUT=$(git -C "${GITOPS_REPO_DIR}" ls-remote --heads origin ${GIT_LOCK_BRANCH})
     if [[ -n "${LS_REMOTE_STDOUT}"  ]]; then
-      echo " - clone_and_lock_git_repo: Lock branch ${GIT_LOCK_BRANCH} currently in use by another process, retry in ${RETRY_DELAY_SECONDS}s"
+      echo "clone_and_lock_git_repo: Lock branch ${GIT_LOCK_BRANCH} currently in use by another process, retry in ${RETRY_DELAY_SECONDS}s"
+      echo "..."
       sleep ${RETRY_DELAY_SECONDS}
       continue
     fi
@@ -346,7 +352,8 @@ function clone_and_lock_target_git_repo() {
 
     # Create the lock branch locally
     echo
-    echo "git: checkout -b ${GIT_LOCK_BRANCH}"
+    echo "- clone_and_lock_git_repo: checkout -b ${GIT_LOCK_BRANCH}"
+    echo "-------------------------------------------------"
     git -C "${GITOPS_REPO_DIR}" checkout -b "${GIT_LOCK_BRANCH}"
 
     # To definitively acquire the "lock", we create and commit a temporary "lock file";
@@ -355,15 +362,18 @@ function clone_and_lock_target_git_repo() {
     touch "${GITOPS_REPO_DIR}/${LOCKFILE_NAME}"
 
     echo
-    echo "git: add ${LOCKFILE_NAME}"
+    echo "- clone_and_lock_git_repo: add ${LOCKFILE_NAME}"
+    echo "-------------------------------------------------"
     git -C "${GITOPS_REPO_DIR}" add ${LOCKFILE_NAME}
 
     echo
-    echo "git: commit -m 'Acquire lock branch'"
+    echo "- clone_and_lock_git_repo: commit -m 'Acquire lock branch'"
+    echo "-------------------------------------------------"
     git -C "${GITOPS_REPO_DIR}" commit -m 'Acquire lock branch'
 
     echo
-    echo "git: push --atomic -u origin ${GIT_LOCK_BRANCH}"
+    echo "- clone_and_lock_git_repo: push --atomic -u origin ${GIT_LOCK_BRANCH}"
+    echo "-------------------------------------------------"
     git -C "${GITOPS_REPO_DIR}" push --atomic -u origin "${GIT_LOCK_BRANCH}"
     GIT_PUSH_RC=$?
 
@@ -372,19 +382,72 @@ function clone_and_lock_target_git_repo() {
       # Register an exit trap to ensure we delete the remote branch whatever happens
       trap "unlock_git_repo ${GIT_LOCK_BRANCH} ${GITOPS_REPO_DIR}" EXIT
       echo ""
-      echo " - clone_and_lock_git_repo: Acquired lock on branch ${GIT_LOCK_BRANCH}; proceeding..."
+      echo "= clone_and_lock_git_repo: acquired lock on branch ${GIT_LOCK_BRANCH}; proceeding..."
+      echo "================================================="
       return 0
     fi 
 
     echo ""
-    echo " - clone_and_lock_git_repo: Failed to acquire Lock branch ${GIT_LOCK_BRANCH}, retry in ${RETRY_DELAY_SECONDS}s"
+    echo "- clone_and_lock_git_repo: failed to acquire Lock branch ${GIT_LOCK_BRANCH}, retry in ${RETRY_DELAY_SECONDS}s"
+    echo "..."
     sleep ${RETRY_DELAY_SECONDS}
 
   done
 
-  echo " - clone_and_lock_git_repo: !!! Failed clone_and_lock_git_repo after ${RETRIES} retries... giving up"
-  exit 1
+  echo "= clone_and_lock_git_repo: non-recoverable failure"
+  echo "================================================="
+  return 1
 
+}
+
+
+# rebases then attempts to push the git repo
+# if the push fails, the rebase and push will be retried after RETRY_DELAY_SECONDS delay up to RETRIES times
+# the retry logic is there in case another process pushes a commit to the repo in between the rebase and push, causing errors like this:
+#    ! [rejected]        master -> master (fetch first)
+#    ! [remote rejected] master -> master (cannot lock ref 'refs/heads/master': is at x but expected y)
+function git_push_with_retries {
+  GITHUB_REPO="$1"
+  GIT_BRANCH="$2"
+  LOCAL_DIR="$3"
+  RETRIES=${4:-10}
+  RETRY_DELAY_SECONDS=${5:-30}
+
+  GITOPS_REPO_DIR="${LOCAL_DIR}/${GITHUB_REPO}"
+
+  for (( c=1; c<="${RETRIES}"; c++ )); do
+
+    echo
+    echo "= git_push_with_retries: attempt ${c} of ${RETRIES}"
+    echo "================================================="
+
+    echo
+    echo "- git_push_with_retries: pull origin $GIT_BRANCH --rebase"
+    echo "-------------------------------------------------"
+    git -C "${GITOPS_REPO_DIR}" pull origin "${GIT_BRANCH}" --rebase
+
+    echo
+    echo "- git_push_with_retries: push -u origin ${GIT_BRANCH}"
+    echo "-------------------------------------------------"
+    git -C "${GITOPS_REPO_DIR}" push -u origin "${GIT_BRANCH}"
+    rc=$?
+    if [[ $rc == "0" ]]; then
+      echo ""
+      echo "= git_push_with_retries: success"
+      echo "================================================="
+      return 0
+    fi
+
+    echo ""
+    echo "- git_push_with_retries: failed (rc: ${rc}), retry in ${RETRY_DELAY_SECONDS}s"
+    echo "..."
+    sleep $RETRY_DELAY_SECONDS
+  done
+
+  echo ""
+  echo "= git_push_with_retries: non-recoverable failure"
+  echo "================================================="
+  return 1
 }
 
 
@@ -399,7 +462,8 @@ function clone_and_lock_target_git_repo() {
 #   fi
 function save_and_unlock_target_git_repo {
   echo
-  echo " - save_and_unlock_target_git_repo"
+  echo "= save_and_unlock_target_git_repo"
+  echo "================================================="
   GITHUB_REPO="$1"
   GIT_BRANCH="$2"
   LOCAL_DIR="$3"
@@ -415,28 +479,34 @@ function save_and_unlock_target_git_repo {
 
   # commit and push all changes
   echo
-  echo "git: add -v ."
+  echo "- save_and_unlock_target_git_repo: add -v ."
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" add -v .
 
   echo
-  echo "git: commit -m ${GIT_COMMIT_MSG} "
+  echo "- save_and_unlock_target_git_repo: commit -m ${GIT_COMMIT_MSG}"
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" commit -m "${GIT_COMMIT_MSG}"
 
   echo
-  echo "git: push -u origin ${GIT_LOCK_BRANCH} "
+  echo "- save_and_unlock_target_git_repo: push -u origin ${GIT_LOCK_BRANCH}"
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" push -u origin "${GIT_LOCK_BRANCH}"
 
   # Merge back to master
   echo
-  echo "git: switch ${GIT_BRANCH}"
+  echo "- save_and_unlock_target_git_repo: switch ${GIT_BRANCH}"
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" switch "${GIT_BRANCH}"
 
   echo
-  echo "git: pull origin $GIT_BRANCH --rebase"
+  echo "- save_and_unlock_target_git_repo: pull origin $GIT_BRANCH --rebase"
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" pull origin $GIT_BRANCH --rebase
 
   echo
-  echo "git: merge --squash ${GIT_LOCK_BRANCH}"
+  echo "- save_and_unlock_target_git_repo: merge --squash ${GIT_LOCK_BRANCH}"
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" merge --squash "${GIT_LOCK_BRANCH}"
 
 
@@ -451,12 +521,13 @@ function save_and_unlock_target_git_repo {
   fi
 
   echo
-  echo "git: commit -m ${GIT_COMMIT_MSG}"
+  echo "- save_and_unlock_target_git_repo:: commit -m ${GIT_COMMIT_MSG}"
+  echo "-------------------------------------------------"
   git -C "${GITOPS_REPO_DIR}" commit -m "${GIT_COMMIT_MSG}" 
 
-  echo
-  echo "git: push -u origin ${GIT_BRANCH}"
-  git -C "${GITOPS_REPO_DIR}" push -u origin "${GIT_BRANCH}"
+
+  git_push_with_retries "${GITHUB_REPO}" "${GIT_BRANCH}" "${LOCAL_DIR}"
+
 
   # unlock_git_repo exit trap function registered in clone_and_lock_target_git_repo
   # takes care of deleting remote branch and local clone
@@ -464,6 +535,11 @@ function save_and_unlock_target_git_repo {
   # (note since this will also delete the repo dir from the system, when the exit trap reruns this script
   # it won't repeat the branch delete (which could cause problems since another process could have since re-created the lock branch))
   unlock_git_repo "${GIT_LOCK_BRANCH}" "${GITOPS_REPO_DIR}"
+
+
+  echo
+  echo "= save_and_unlock_target_git_repo: success"
+  echo "================================================="
 
 }
 
