[patch] add trap to other functions

diff --git a/image/cli/mascli/functions/gitops_deprovision_rosa b/image/cli/mascli/functions/gitops_deprovision_rosa
--- a/image/cli/mascli/functions/gitops_deprovision_rosa
+++ b/image/cli/mascli/functions/gitops_deprovision_rosa
@@ -52,6 +52,9 @@ function gitops_deprovision_rosa(){
     gitops_deprovision_rosa_interactive
   fi
 
+  # catch errors
+  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR
+
   echo
   reset_colors
   echo_h2 "Review Settings"
diff --git a/image/cli/mascli/functions/gitops_suite b/image/cli/mascli/functions/gitops_suite
--- a/image/cli/mascli/functions/gitops_suite
+++ b/image/cli/mascli/functions/gitops_suite
@@ -345,7 +345,8 @@ function gitops_suite() {
     gitops_suite_interactive
   fi
 
-  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE: $LINENO command: $BASH_COMMMAND exited with $?"; exit 1' ERR
+  # catch errors
+  trap 'echo "[ERROR] Error occurred at $BASH_SOURCE, line $LINENO, exited with $?"; exit 1' ERR
 
   export DOMAIN=${MAS_DOMAIN}
   if [[ "${DNS_PROVIDER}" == "cis" ]]; then
