Merge master branch into eps-csi-driver-operator (#2048)
Co-authored-by: David Parker <parkerda@uk.ibm.com>
Co-authored-by: Anil Prajapati <169060963+anilprajapatiibm@users.noreply.github.com>
Co-authored-by: Alfishan Salar <Alfishan@gmail.com>
Co-authored-by: Mahammad Alfishan Salar <alfishan@ibm.com>
Co-authored-by: mnivedithaa <mnivedithaa@gmail.com>
Co-authored-by: unnati-solanki-git <131964221+unnati-solanki-git@users.noreply.github.com>
Co-authored-by: Hardik Prajapati <Hardik.Prajapati@ibm.com>
Co-authored-by: karol-czarnecki <112193189+karol-czarnecki@users.noreply.github.com>
Co-authored-by: Társis Augusto <64480693+terc1997@users.noreply.github.com>
Co-authored-by: gabrielbonamicoibm <146848045+gabrielbonamicoibm@users.noreply.github.com>
Co-authored-by: Abhishekkushawaha <159771922+Abhishekkushawaha@users.noreply.github.com>
Co-authored-by: Sumit Jain <59478347+sumitjain-1901@users.noreply.github.com>
Co-authored-by: Drashti-Malviya <drashti.malviya1207@gmail.com>
Co-authored-by: jainyjoseph <jainy587@gmail.com>
Co-authored-by: leo-miran <105313348+leo-miran@users.noreply.github.com>
Co-authored-by: Daniel Istrate <16302386+istrate@users.noreply.github.com>
Co-authored-by: Daniel Istrate <Daniel.Istrate1@ibm.com>
Co-authored-by: stonepd <stonepd@uk.ibm.com>
Co-authored-by: Jasmin Makwana <jasminmakwana1999@gmail.com>
Co-authored-by: Parveen Kumar <parveenkumar@ibm.com>
Co-authored-by: Divyesh-Khokhar <divyesh.k@ibm.com>
Co-authored-by: aniket.choudhary@ibm.com <aniket.choudhary@ibm.com>
Co-authored-by: Anil Prajapati <Anil.Prajapati@ibm.com>
Co-authored-by: joshiricha444 <37139779+joshiricha444@users.noreply.github.com>
Co-authored-by: Andre Ferreira Guimaraes Junior <andrefgj@gmail.com>
Co-authored-by: Hita-Pandya <Hita.Pandya@ibm.com>
Co-authored-by: Ian Boden <82514609+IanBoden@users.noreply.github.com>
Co-authored-by: amitpandey0217 <amit.pandey17@ibm.com>
Co-authored-by: AquaD17 <112812380+dixitgsathwara@users.noreply.github.com>
Co-authored-by: Dixit Sathwara <Dixit.Sathwara1@ibm.com>
Co-authored-by: Bhautiksinh Vala <94218990+Bhautik-Vala@users.noreply.github.com>

diff --git a/image/cli/mascli/functions/mirror_images_common b/image/cli/mascli/functions/mirror_images_common
--- a/image/cli/mascli/functions/mirror_images_common
+++ b/image/cli/mascli/functions/mirror_images_common
@@ -29,43 +29,6 @@ function show_mirror_status() {
   fi
 }
 
-function mirror_to_registry_help_header() {
-  [[ -n "$1" ]] && echo_warning "$1"
-  reset_colors
-  cat << EOM
-Usage:
-  mas mirror-images [options]
-Where ${COLOR_YELLOW}specified${TEXT_RESET} each option may also be defined by setting the appropriate environment variable.
-When no options are specified on the command line, interactive-mode will be enabled by default.
-
-Mirror Mode (Required):
-  -m, --mode ${COLOR_YELLOW}MIRROR_MODE${TEXT_RESET}                         Operation mode (direct, to-filesystem, from-filesystem)
-  -d, --dir ${COLOR_YELLOW}MIRROR_WORKING_DIR${TEXT_RESET}                   Working directory for the mirror process
-
-Registry Details (Required):
-  -H, --host ${COLOR_YELLOW}REGISTRY_PUBLIC_HOST${TEXT_RESET}                 Hostname of the target registry
-  -P, --port ${COLOR_YELLOW}REGISTRY_PUBLIC_PORT${TEXT_RESET}                 Port number for the target registry
-  -u, --username ${COLOR_YELLOW}REGISTRY_USERNAME${TEXT_RESET}                Username to authenticate to the target registry
-  -p, --password ${COLOR_YELLOW}REGISTRY_PASSWORD${TEXT_RESET}                Password to authenticate to the target registry
-
-Registry Prefix (Optional):
-  -x, --prefix ${COLOR_YELLOW}REGISTRY_PREFIX${TEXT_RESET}                    Prefix for the mirror image
-
-AWS Elastic Container Registry (Optional):
-  -r, --aws-ecr-region ${COLOR_YELLOW}REGISTRY_ECR_AWS_REGION${TEXT_RESET}    The AWS region if the target registry is Elastic Container Registry
-  -e, --target-is-ecr                                                         Indicate that the target registry is Elastic Container Registry
-
-Source Registry Entitlements (Required based on what content you choose to mirror):
-      --ibm-entitlement ${COLOR_YELLOW}IBM_ENTITLEMENT_KEY${TEXT_RESET}       IBM Entitlement Key
-      --artifactory-username ${COLOR_YELLOW}ARTIFACTORY_USERNAME${TEXT_RESET} Artifactory Username
-      --artifactory-token ${COLOR_YELLOW}ARTIFACTORY_TOKEN${TEXT_RESET}       Artifactory Token
-
-Maximo Operator Catalog Selection (Optional):
-  -c, --catalog ${COLOR_YELLOW}MAS_CATALOG_VERSION${TEXT_RESET}               Maximo Operator Catalog Version to mirror (e.g. v9-240625-amd64)
-  -C, --channel ${COLOR_YELLOW}MAS_CHANNEL${TEXT_RESET}                       Maximo Application Suite Channel to mirror (e.g. 9.1.x)
-EOM
-}
-
 function mirror_to_registry_interactive_common() {
   load_config
   echo
@@ -148,6 +111,8 @@ function mirror_to_registry_common() {
   export ARTIFACTORY_USERNAME
   export ARTIFACTORY_TOKEN
 
+  set_target_arch
+
   echo
   reset_colors
   echo_h2 "Review Settings"
@@ -171,6 +136,7 @@ function mirror_to_registry_common() {
   echo_h4 "IBM Operator Catalog" "    "
   echo_reset_dim "Catalog Version ..................... ${COLOR_MAGENTA}${MAS_CATALOG_VERSION}"
   echo_reset_dim "MAS Update Channel .................. ${COLOR_MAGENTA}${MAS_CHANNEL}"
+  echo_reset_dim "Target Architecture ................. ${COLOR_MAGENTA}${MIRROR_SINGLE_ARCH}"
 }
 
 function confirm_mirror() {
@@ -190,4 +156,17 @@ function confirm_mirror() {
 
   export ARTIFACTORY_USERNAME=""
   export ARTIFACTORY_TOKEN=""
+}
+
+function set_target_arch() {
+  if [[ "$MAS_CATALOG_VERSION" == *"amd64"* ]]; then
+    export MIRROR_SINGLE_ARCH="amd64"
+  elif [[ "$MAS_CATALOG_VERSION" == *"ppc64le"* ]]; then
+    export MIRROR_SINGLE_ARCH="ppc64le"
+  elif [[ "$MAS_CATALOG_VERSION" == *"s390x"* ]]; then
+    export MIRROR_SINGLE_ARCH="s390x"
+  else
+    echo -e "${COLOR_RED}Usage Error: Could not determine target architecture from catalog version: $MAS_CATALOG_VERSION${TEXT_RESET}\n"
+    exit 1
+  fi
 }
