[patch] test fix 1

diff --git a/image/cli/mascli/functions/pipeline_config_additional_configs b/image/cli/mascli/functions/pipeline_config_additional_configs
--- a/image/cli/mascli/functions/pipeline_config_additional_configs
+++ b/image/cli/mascli/functions/pipeline_config_additional_configs
@@ -37,11 +37,12 @@ function config_pipeline_additional_configs() {
     done
 
     echo
-    prompt_for_confirm "Are these the correct configuration files to apply?" || echo "exit 0" && exit 0
-    echo "exit 1"
+    prompt_for_confirm "Are these the correct configuration files to apply?" || echo "Additional configuration files not confirmed! Aborting ..." && exit 0
+    echo "Copying additional configuration files to $LOCAL_MAS_CONFIG_DIR ..."
     cp $DIR/templates/additional-configs.yaml $CONFIG_DIR/additional-configs-$MAS_INSTANCE_ID.yaml
     python3 $DIR/tools/cfgmgr add $CONFIG_DIR/additional-configs-$MAS_INSTANCE_ID.yaml $LOCAL_MAS_CONFIG_DIR
     echo
+    return
   else
     LOCAL_MAS_CONFIG_DIR=""
   fi
