[patch] add a fail check if invalid catalog source

diff --git a/image/cli/mascli/functions/update b/image/cli/mascli/functions/update
--- a/image/cli/mascli/functions/update
+++ b/image/cli/mascli/functions/update
@@ -81,7 +81,7 @@ function validate_existing_mongo() {
     # Lookup existing MongoDb instance
     MONGODB_CURRENT_VERSION=`oc get mongodbcommunity.mongodbcommunity.mongodb.com -A -o jsonpath='{.items[0].status.version}' 2> /dev/null`
     # Target mongo version will be defined by chosen catalog/casebundle
-    MONGODB_TARGET_VERSION=`yq -r .mongo_extras_version_default ansible-devops/common_vars/casebundles/${MAS_CATALOG_VERSION}.yml`
+    MONGODB_TARGET_VERSION=`yq -r .mongo_extras_version_default ansible-devops/common_vars/casebundles/${MAS_CATALOG_VERSION}.yml` || echo -e "Not able to find MongoDB version from '$MAS_CATALOG_VERSION', make sure you are choosing a valid MAS catalog!" && exit 1
 
     MONGODB_CURRENT_MAJORMINOR_VERSION=${MONGODB_CURRENT_VERSION:0:3}
     MONGODB_TARGET_MAJORMINOR_VERSION=${MONGODB_TARGET_VERSION:0:3}
@@ -98,7 +98,7 @@ function validate_existing_mongo() {
         MONGODB_V5_UPGRADE=true
         echo
       else
-        if [[ -z "$MONGODB_V5_UPGRADE" ]] ; then # if 'mas update -c v8-231128-amd64 --no-confirm' but no '--mongodb-v5-upgrade' then we fail as user must consent about the mongodb upgrade
+        if [[ -z "$MONGODB_V5_UPGRADE" ]] ; then # if 'mas update -c v8-240130-amd64 --no-confirm' but no '--mongodb-v5-upgrade' then we fail as user must consent about the mongodb upgrade
         echo
         echo -e "${COLOR_RED}By choosing '$MAS_CATALOG_VERSION' catalog, you must confirm MongoDB upgrade to version 5.${TEXT_RESET}"
         echo -e "${COLOR_RED}Add '--mongodb-v5-upgrade' argument to the 'mas update' command in order to continue.${TEXT_RESET}"
