[patch] Preparation for UDS to DRO migration in Feb update (#726)
Co-authored-by: Daniel Istrate <16302386+istrate@users.noreply.github.com>
Co-authored-by: David Parker <parkerda@uk.ibm.com>

diff --git a/image/cli/mascli/functions/update b/image/cli/mascli/functions/update
--- a/image/cli/mascli/functions/update
+++ b/image/cli/mascli/functions/update
@@ -18,6 +18,7 @@ Update Dependencies (Optional):
   --mongodb-v5-upgrade ${COLOR_YELLOW}MONGODB_V5_UPGRADE${TEXT_RESET} Confirms that Mongo can be upgraded to version 5 if needed as part of the update
   --kafka-namespace ${COLOR_YELLOW}KAFKA_NAMESPACE${TEXT_RESET}       Namespace where Kafka operator and instance will be updated
   --kafka-provider ${COLOR_YELLOW}KAFKA_PROVIDER${TEXT_RESET}         Set Kafka provider. Supported options are 'redhat' (Red Hat AMQ Streams), or 'strimzi'
+  --dro-migration  ${COLOR_YELLOW}DRO_MIGRATION${TEXT_RESET}          Confirm the removal of UDS and replacement with DRO as part of the update
 
 Other Commands:
       --no-confirm                      Launch the update without prompting for confirmation
@@ -99,6 +100,84 @@ function validate_existing_mongo() {
   fi
 }
 
+# Validate UDS to DRO Migration
+# -----------------------------------------------------------------------------
+
+function validate_dro_migration(){
+  # warn about DRO migration if UDS is running and MAS catalog is January 2024 or newer
+  MAS_CATALOG_DATE=${MAS_CATALOG_VERSION:3:6}
+
+  if [[ $MAS_CATALOG_DATE -ge 240227 ]]; then
+    echo -e "${COLOR_YELLOW}Verifing UDS status."
+    # If Jan catalog is detected, set DRO_MIGRATION Flag to True
+    UDS_NAMESPACE="ibm-common-services"
+    UDS_CSV=`oc get csv -n "${UDS_NAMESPACE}" | grep user-data-services  | awk '{print $1}'`
+
+    if [[ -n $UDS_CSV ]]; then
+      UDS_STATUS=`oc get csv -n "${UDS_NAMESPACE}" "${UDS_CSV}" -o jsonpath='{.status.phase}'`
+
+      if [[ $UDS_STATUS = *'Succeeded'* ]]; then
+        echo -e "${COLOR_YELLOW}UDS is currently running in namespace ${UDS_NAMESPACE}."
+        echo -e "UDS will be uninstalled and MAS will migrate to use DRO (Data Reporter Operator). All compatible bascfg configuration will be updated and configured to use DRO ${COLOR_RESET}"
+        echo
+
+        if [[ "$NO_CONFIRM" != "true" ]]; then
+          prompt_for_confirm_default_yes "Do you want to proceed with uninstalling UDS and migrate to DRO?" DRO_MIGRATION
+        fi
+
+        if [[ "$DRO_MIGRATION" == "true" ]]; then
+          ## Check all avaliable Suite Instances versions , if any of them is 8.9.x cancel the dro migration. Exit mas update throw error.
+          for suite_namespace in $(oc get Suite --all-namespaces --ignore-not-found -o jsonpath='{.items[*].metadata.namespace}')
+          do
+            suite_name=`oc get Suite -n ${suite_namespace}  -o NAME`
+            suite_version=`oc get ${suite_name} -n ${suite_namespace} -o jsonpath='{.status.versions.reconciled}'`
+
+            if [[ $suite_version = 9.* ]] || [[ $suite_version = 8.11.* ]] || [[ $suite_version = 8.10.* ]]
+            then
+              echo -e "${COLOR_YELLOW}${suite_namespace} with MAS version ${suite_version} is compatible for DRO migration"
+
+              ## Check if the BASCFG url has a local UDS on all instances, if not then exit and throw error
+              bascfg_name=`oc get BasCfg -n ${suite_namespace} -o NAME`
+              bas_url=`oc get ${bascfg_name} -n ${suite_namespace} -o jsonpath='{.spec.config.url}'`
+              uds_url=`oc get route uds-endpoint -n ibm-common-services -o jsonpath='{.spec.host}'`
+
+              if [[ -z ${uds_url} ]]
+              then
+                echo -e "${COLOR_RED}UDS route is empty, Please fix your UDS installation to proceed with DRO migration, exiting mas update"
+                exit 1
+              fi
+
+              if [[ ${bas_url} == *${uds_url}* ]]
+              then
+                echo -e "${COLOR_YELLOW}UDS Configuration on ${suite_namespace} is compatible for DRO migration"
+              else
+                echo -e "${COLOR_RED}${suite_namespace} appears to use a Remote UDS that is not running locally on this cluster. This setup is not compatible for DRO migration, exiting mas update"
+                exit 1
+              fi
+            else
+              echo -e "${COLOR_RED}${suite_namespace} with MAS version ${suite_version} does not support DRO, you must run mas upgrade to upgrade this instance to at least MAS 8.10, exiting mas update"
+              exit 1
+            fi
+            echo
+          done
+        else
+          echo -e "${COLOR_RED}You must accept the migration from UDS to DRO to continue with the update to ${MAS_CATALOG_VERSION}"
+          exit 1
+        fi
+      else
+        echo -e "${COLOR_RED}UDS is in Error state. Please fix your UDS installation to proceed with DRO migration, exiting mas update"
+        exit 1
+      fi
+    else
+      DRO_MIGRATION="false"
+      echo -e "${COLOR_YELLOW}UDS does not exist, skipping DRO migration and proceeding with mas update"
+    fi
+  else
+    DRO_MIGRATION="false"
+  fi
+
+}
+
 # Auto-detect Grafana
 # -----------------------------------------------------------------------------
 # Detects whether Grafana V4 Operator is in the target cluster and prints a
@@ -165,8 +244,13 @@ function validate_update() {
     fi
   fi
 
+
+  # Validates UDS to DRO migration only if UDS is running and January catalog or more recent is used
+  validate_dro_migration
+
   # Confirm Grafana Operator upgrade
   detect_grafana_update
+
 
   # Lookup for OCP console route
   if [[ -z "$OCP_CONSOLE_ROUTE" ]]; then
@@ -247,6 +331,9 @@ function update_noninteractive() {
         ;;
       --kafka-provider)
         KAFKA_PROVIDER=$1 && shift
+        ;;
+      --dro-migration)
+        DRO_MIGRATION=true
         ;;
       --no-confirm)
         NO_CONFIRM=true
@@ -339,6 +426,7 @@ function update() {
   export KAFKA_PROVIDER
   export CERT_MANAGER_PROVIDER
   export CERT_MANAGER_ACTION
+  export DRO_MIGRATION
   export GRAFANA_V5_UPGRADE
 
   echo_h2 "Review Settings"
@@ -386,6 +474,15 @@ function update() {
     echo_reset_dim "Kafka ($KAFKA_PROVIDER_NAME ${COLOR_GREEN}Yes ($KAFKA_NAMESPACE)${TEXT_RESET}"
   else
     echo_reset_dim "Kafka ...................................... ${COLOR_RED}No${TEXT_RESET}"
+  fi
+
+  # DRO Migration
+
+  if [ "$DRO_MIGRATION" = "true" ]; then
+    echo_reset_dim "DRO Migration .............................. ${COLOR_GREEN}Yes${TEXT_RESET}"
+  else
+    echo_reset_dim "DRO Migration .............................. ${COLOR_RED}No${TEXT_RESET}"
+
   fi
 
   # Grafana Operator
