Add remote ocp call to update

diff --git a/tekton/src/tasks/dependencies/ocp-verify.yml.j2 b/tekton/src/tasks/dependencies/ocp-verify.yml.j2
--- a/tekton/src/tasks/dependencies/ocp-verify.yml.j2
+++ b/tekton/src/tasks/dependencies/ocp-verify.yml.j2
@@ -27,6 +27,18 @@ spec:
       type: string
       default: ""
 
+    - name: remote_ocp_cluster
+      type: string
+      default: ""
+    - name: remote_ocp_type
+      type: string
+      default: ""
+    - name: rosa_cluster_admin_password
+      type: string
+      default: ""
+    - name: rosa_token
+      type: string
+      default: ""
 
   stepTemplate:
     env:
@@ -48,9 +60,25 @@ spec:
 
   steps:
     - name: ocp-verify
-      command:
-        - /opt/app-root/src/run-role.sh
-        - ocp_verify
+      script: |
+        #!/usr/bin/env bash
+
+        if [ ! -z $REMOTE_OCP_CLUSTER ];then
+          echo "Logging into $(params.remote_ocp_cluster)"
+          export CLUSTER_NAME=$(params.remote_ocp_cluster)
+          export CLUSTER_TYPE=$(params.remote_ocp_type)
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(params.rosa_cluster_admin_password)
+          export ROSA_TOKEN=$(params.rosa_token)
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed to $(params.remote_ocp_cluster)"
+            exit 1
+          fi
+        fi
+
+        /opt/app-root/src/run-role.sh ocp_verify
+
       image: quay.io/ibmmas/cli:latest
       imagePullPolicy: $(params.image_pull_policy)
       workingDir: /workspace/configs
