[patch] - adding error hadling to mustgather scripts

diff --git a/image/cli/mascli/must-gather/mg-collect-reconcile-logs b/image/cli/mascli/must-gather/mg-collect-reconcile-logs
--- a/image/cli/mascli/must-gather/mg-collect-reconcile-logs
+++ b/image/cli/mascli/must-gather/mg-collect-reconcile-logs
@@ -1,30 +1,34 @@
 #!/bin/bash
-set -e
+# set -e
 
 NAMESPACE=$1
 LABEL_SELECTOR=$2
 LABEL_VALUE=$3
 OUTPUT_DIR=$4
 
+echo "  - Collecting reconcile logs from '$LABEL_SELECTOR':'$LABEL_VALUE'"
+
 POD=$(oc -n $NAMESPACE get pods -l "$LABEL_SELECTOR=$LABEL_VALUE" -o jsonpath="{.items[0].metadata.name}" 2>/dev/null) || { echo "   - Error fetching pods with label: $LABEL_SELECTOR=$LABEL_VALUE"; exit 0; }
 
+set +e
 LOGFILES=$(oc -n $NAMESPACE exec $POD -- find /tmp/ansible-operator/runner/ -name stdout 2>/dev/null)
 if [[ "$?" == "1" ]]; then
-  echo "   - Error finding /tmp/ansible-operator/runner/ for: $POD $LABEL_SELECTOR=$LABEL_VALUE"
+  echo "    - Error finding /tmp/ansible-operator/runner/ for: $POD $LABEL_SELECTOR=$LABEL_VALUE"
   exit 0
 fi
+set -e
 
 TMP_DIR=${OUTPUT_DIR}/tmp-$LABEL_VALUE
 mkdir -p $TMP_DIR
 
-echo "  - Collecting reconcile logs from '$LABEL_SELECTOR':'$LABEL_VALUE'"
+
 oc -n $NAMESPACE exec $POD -- tar -czf - $LOGFILES > $TMP_DIR/ansible-logs-$LABEL_VALUE.tgz 2>/dev/null
-tar -xf $TMP_DIR/ansible-logs-$LABEL_VALUE.tgz -C $TMP_DIR  --no-same-owner 2>/dev/null  || { echo "   - Error to untar $TMP_DIR/ansible-logs-$LABEL_VALUE.tgz"; exit 0; }
+tar -xf $TMP_DIR/ansible-logs-$LABEL_VALUE.tgz -C $TMP_DIR  --no-same-owner 2>/dev/null  || { echo "   - Error to untar $TMP_DIR/ansible-logs-$LABEL_VALUE.tgz"; }
 
 if [[ "$?" == "0" ]]; then
   rm $TMP_DIR/ansible-logs-$LABEL_VALUE.tgz
 else
-  echo_warning "    - Unable to get reconcile logs from $POD"
+  echo "    - Unable to get reconcile logs from $POD"
 fi
 
 for API_DIR in $TMP_DIR/tmp/ansible-operator/runner/*
