[patch] improve iot must gather log collection

diff --git a/image/cli/mascli/must-gather/mg-collect-reconcile-logs b/image/cli/mascli/must-gather/mg-collect-reconcile-logs
--- a/image/cli/mascli/must-gather/mg-collect-reconcile-logs
+++ b/image/cli/mascli/must-gather/mg-collect-reconcile-logs
@@ -17,13 +17,18 @@ TMP_DIR=${OUTPUT_DIR}/tmp-$CONTROL_PLANE
 mkdir -p $TMP_DIR
 
 echo "  - Collecting reconcile logs from control plane '$CONTROL_PLANE'"
+set +e # the tar command may give warnings if files no longer exist, and they get cycled by the operator.
 oc -n $NAMESPACE exec $POD -- tar -czf - $LOGFILES > $TMP_DIR/ansible-logs-$CONTROL_PLANE.tgz 2> /dev/null
+if [[ "$?" != "0" ]]; then
+  echo "    - Incomplete reconcile logs from $POD"
+fi
 tar -xf $TMP_DIR/ansible-logs-$CONTROL_PLANE.tgz -C $TMP_DIR 2> /dev/null
 if [[ "$?" == "0" ]]; then
   rm $TMP_DIR/ansible-logs-$CONTROL_PLANE.tgz
 else
-  echo_warning "    - Unable to get reconcile logs from $POD"
+  echo "    - Unable to get reconcile logs from $POD"
 fi
+set -e
 
 for API_DIR in $TMP_DIR/tmp/ansible-operator/runner/*
 do
