[patch] - adding error handling

diff --git a/image/cli/mascli/must-gather/mg-collect-resources b/image/cli/mascli/must-gather/mg-collect-resources
--- a/image/cli/mascli/must-gather/mg-collect-resources
+++ b/image/cli/mascli/must-gather/mg-collect-resources
@@ -60,9 +60,9 @@ if [[ "$NO_DETAIL" == "false" ]]; then
             # echo "    - Collecting $RESOURCE"
             RESOURCE_NAME=$(echo ${RESOURCE} | cut -d '/' -f 2)
 
-            oc ${NAMESPACE_FLAG} get ${RESOURCE} -o yaml > ${RESOURCE_DIR}/${RESOURCE_NAME}.yaml
+            oc ${NAMESPACE_FLAG} get ${RESOURCE} -o yaml > ${RESOURCE_DIR}/${RESOURCE_NAME}.yaml || { echo "Error fetching resource: ${RESOURCE}"; exit 0; }
         done
     else
-        oc get ${RESOURCE_TYPE} ${ALL_NAMESPACES} -o yaml > ${RESOURCE_DIR}/all-namespaces.yaml
+        oc get ${RESOURCE_TYPE} ${ALL_NAMESPACES} -o yaml > ${RESOURCE_DIR}/all-namespaces.yaml || { echo "Error fetching resource: ${RESOURCE_TYPE}"; exit 0; }
     fi
 fi
