[patch] db2 logs

diff --git a/image/cli/mascli/must-gather/mg-collect-manage-logs b/image/cli/mascli/must-gather/mg-collect-manage-logs
--- a/image/cli/mascli/must-gather/mg-collect-manage-logs
+++ b/image/cli/mascli/must-gather/mg-collect-manage-logs
@@ -26,28 +26,46 @@ mkdir -p "$OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files"
 # Copying files to folder
 oc cp $NAMESPACE/$POD_NAME:log $OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files --retries=-1
 
-
-# Getting Server Bundle Pod Files
+# Getting db2u Pod Files
 # =========================
-echo "- ${COLOR_BLUE} Getting Server Bundle Pod Files${TEXT_RESET}"
-POD_NAME=$(oc -n $NAMESPACE get pods -l "mas.ibm.com/appType= serverBundle" -o jsonpath="{.items[*].metadata.name}")
-for POD in ${POD_NAME[@]}; do
-  if [[ "$POD_NAME" == "" ]]; then
-    echo_warning "Server Bundle pod was not found"
-    exit 1
-  fi
-  # Creating folder(s)
-  INSTANCE_ID=$(echo ${NAMESPACE%-*})
-  INSTANCE_ID=$(echo ${INSTANCE_ID#*-})
-  APP=$(echo ${POD%-*}) #removing 2nd ID
-  APP=$(echo ${APP%-*}) #removing 1st ID
-    if [[ "$APP" == "$INSTANCE_ID" ]]; then
-       APP=$(echo ${POD%-*}) #removing 2nd ID
-    fi
-  # mkdir -p "$OUTPUT_DIR/resources/$NAMESPACE/pods/$APP/logs" #it will be overwritten when a new Pods folder will be created to keeps pods info (yaml, txt and logs)
-  mkdir -p "$OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files" 
+echo "- ${COLOR_BLUE} Getting db2u Pod Files${TEXT_RESET}"
+POD_NAME=$(oc -n db2u get pods -l "type=engine" -o jsonpath="{.items[*].metadata.name}")
 
-  # Copying files to folder
-  oc cp $NAMESPACE/$POD:logs $OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files --retries=-1
+if [[ "$POD_NAME" == "" ]]; then
+  echo_warning "db2u pod was not found"
+  exit 1
+fi
+
+# Creating folder
+APP=$(echo ${POD_NAME%-*}) #removing 2nd ID
+APP=$(echo ${APP%-*}) #removing 1st ID
+mkdir -p "$OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files" 
+
+# Copying files to folder
+oc cp $NAMESPACE/$POD_NAME:log $OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files --retries=-1
+
+
+# # Getting Server Bundle Pod Files
+# # =========================
+# echo "- ${COLOR_BLUE} Getting Server Bundle Pod Files${TEXT_RESET}"
+# POD_NAME=$(oc -n $NAMESPACE get pods -l "mas.ibm.com/appType= serverBundle" -o jsonpath="{.items[*].metadata.name}")
+# for POD in ${POD_NAME[@]}; do
+#   if [[ "$POD_NAME" == "" ]]; then
+#     echo_warning "Server Bundle pod was not found"
+#     exit 1
+#   fi
+#   # Creating folder(s)
+#   INSTANCE_ID=$(echo ${NAMESPACE%-*})
+#   INSTANCE_ID=$(echo ${INSTANCE_ID#*-})
+#   APP=$(echo ${POD%-*}) #removing 2nd ID
+#   APP=$(echo ${APP%-*}) #removing 1st ID
+#     if [[ "$APP" == "$INSTANCE_ID" ]]; then
+#        APP=$(echo ${POD%-*}) #removing 2nd ID
+#     fi
+#   # mkdir -p "$OUTPUT_DIR/resources/$NAMESPACE/pods/$APP/logs" #it will be overwritten when a new Pods folder will be created to keeps pods info (yaml, txt and logs)
+#   mkdir -p "$OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files" 
+
+#   # Copying files to folder
+#   oc cp $NAMESPACE/$POD:logs $OUTPUT_DIR/resources/$NAMESPACE/pods_files/$APP/files --retries=-1
 done
 exit 0
