[patch] [MASCORE-1684] Initial commit  update the tasks to include additional params, remove secret keys

diff --git a/tekton/src/tasks/gitops/gitops-deprovision-efs.yml.j2 b/tekton/src/tasks/gitops/gitops-deprovision-efs.yml.j2
--- a/tekton/src/tasks/gitops/gitops-deprovision-efs.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-deprovision-efs.yml.j2
@@ -14,6 +14,12 @@ spec:
     - name: cloud_provider
       type: string
       default: aws
+    - name: cluster_url
+      type: string
+      default: ""
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-deprovision-efs
     env:
@@ -25,6 +31,16 @@ spec:
         value: $(params.mas_instance_id)
       - name: CLOUD_PROVIDER
         value: $(params.cloud_provider)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
+    envFrom:
+      - configMapRef:
+          name: environment-properties
+          optional: true
+      - secretRef:
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -32,16 +48,40 @@ spec:
         aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
         aws configure set default.region $(params.avp_aws_secret_region)
         
-        export ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed so assume there is no efs to deprovision, exiting.."
-          exit 0
+        ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
+        if [ -f $ROSA_CONFIG ]; then
+          echo "oc login : via ROSA_CONFIG"
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed so assume there is no efs to deprovision, exiting.."
+            exit 0
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          echo "oc login : OCP_USERNAME=$OCP_USERNAME OCP_SERVER=$OCP_SERVER OCP_PASSWORD=${OCP_PASSWORD:0:4}<snip> ..."
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed so assume there is no efs to deprovision, exiting.."
+            exit 0
+          fi
+        else
+          echo "oc login : via ocp_login"
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed so assume there is no efs to deprovision, exiting.."
+            exit 0
+          fi
         fi
+
 
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
