[patch] handle return codes (#928)

diff --git a/tekton/src/tasks/gitops/gitops-deprovision-rosa.yml.j2 b/tekton/src/tasks/gitops/gitops-deprovision-rosa.yml.j2
--- a/tekton/src/tasks/gitops/gitops-deprovision-rosa.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-deprovision-rosa.yml.j2
@@ -33,6 +33,11 @@ spec:
         export ROSA_CONFIG_DIR=/workspace/configs/tmp-rosa-deprovision
         mkdir -p $ROSA_CONFIG_DIR
         mas gitops-deprovision-rosa -c $(params.cluster_name)
+        RC=$?
+        if [ $RC -ne 0 ]; then
+          echo "mas gitops-deprovision-rosa failed with error $RC"
+          exit $RC
+        fi
 
         echo "Removing rosa-$(params.cluster_name)-details.yaml"
         rm -f /workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
diff --git a/tekton/src/tasks/gitops/gitops-mas-initiator.yml.j2 b/tekton/src/tasks/gitops/gitops-mas-initiator.yml.j2
--- a/tekton/src/tasks/gitops/gitops-mas-initiator.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-mas-initiator.yml.j2
@@ -250,7 +250,13 @@ spec:
         fi
 
         echo "git: Adding all files in $TARGET_LOCAL_DIR working directory"
-        export FILES_ADDED=$(git add -v . | wc -l | xargs)
+        FILES_ADDED_OUTPUT="$(git add -v .)"
+        return_code=$?
+        if [ $return_code -ne 0 ]; then
+          echo "git: Add files failed with error: $return_code"
+          exit $return_code
+        fi
+        export FILES_ADDED=$(echo "$FILES_ADDED_OUTPUT" | awk NF | wc -l | xargs)
         echo "git: Added ${FILES_ADDED} files"
 
         export COMMIT_MSG="gitops-initiator deploy for $CLUSTER_NAME"
