[patch] minor fix

diff --git a/tekton/src/tasks/gitops/gitops-deprovision-suite-config.yml.j2 b/tekton/src/tasks/gitops/gitops-deprovision-suite-config.yml.j2
--- a/tekton/src/tasks/gitops/gitops-deprovision-suite-config.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-deprovision-suite-config.yml.j2
@@ -58,7 +58,7 @@ spec:
   steps:
     - args:
       - |-
-        mkdir -p /workspace/configs/$GITHUB_REPO/deprovision-suite-config
+        mkdir -p /tmp/deprovision-suite-config
 
         git config --global user.name "yourUsername"
         git config --global user.email "you@example.com"
@@ -69,7 +69,11 @@ spec:
         export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
         export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
         oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-
+        OC_RC=$?
+        if [ $OC_RC -ne 0 ]; then
+          echo "oc login failed, exiting with error.."
+          exit 1
+        fi
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
 
@@ -81,7 +85,7 @@ spec:
 
         mas gitops-deprovision-suite-config -a $ACCOUNT -c $CLUSTER_NAME -m $MAS_INSTANCE_ID \
         --secrets-path $SECRET_PATH \
-        --dir /workspace/configs/$GITHUB_REPO/deprovision-suite-config \
+        --dir /tmp/deprovision-suite-config \
         --github-push \
         --github-host $GITHUB_HOST \
         --github-org $GITHUB_ORG \
diff --git a/tekton/src/tasks/gitops/gitops-init-efs.yml.j2 b/tekton/src/tasks/gitops/gitops-init-efs.yml.j2
--- a/tekton/src/tasks/gitops/gitops-init-efs.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-init-efs.yml.j2
@@ -40,6 +40,17 @@ spec:
         aws configure set aws_secret_access_key $(params.avp_aws_secret_key)
         aws configure set default.region $(params.avp_aws_secret_region)
 
+        export ROSA_CONFIG=/workspace/configs/tmp-rosa-init/rosa-$(params.cluster_name)-details.yaml
+        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+        OC_RC=$?
+        if [ $OC_RC -ne 0 ]; then
+          echo "oc login failed, exiting with error.."
+          exit 1
+        fi
+
         mas gitops-init-efs -c $CLUSTER_NAME -m $MAS_INSTANCE_ID \
         --cloud-provider $CLOUD_PROVIDER \
         --aws-region $SM_AWS_REGION \
diff --git a/tekton/src/tasks/gitops/gitops-init-kafka-config.yml.j2 b/tekton/src/tasks/gitops/gitops-init-kafka-config.yml.j2
--- a/tekton/src/tasks/gitops/gitops-init-kafka-config.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-init-kafka-config.yml.j2
@@ -60,7 +60,7 @@ spec:
   steps:
     - args:
       - |-
-        mkdir -p /workspace/configs/$GITHUB_REPO/init-kafka-config
+        mkdir -p /tmp/init-kafka-config
 
         aws configure set aws_access_key_id $(params.avp_aws_access_key)
         aws configure set aws_secret_access_key $(params.avp_aws_secret_key)
@@ -75,6 +75,11 @@ spec:
         export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
         export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
         oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+        OC_RC=$?
+        if [ $OC_RC -ne 0 ]; then
+          echo "oc login failed , exiting with error.."
+          exit 1
+        fi
 
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
@@ -87,7 +92,7 @@ spec:
 
         mas gitops-init-kafka-config -a $ACCOUNT -c $CLUSTER_NAME -m $MAS_INSTANCE_ID \
         --secrets-path $SECRET_PATH \
-        --dir /workspace/configs/$GITHUB_REPO/init-kafka-config \
+        --dir /tmp/init-kafka-config \
         --github-push \
         --github-host $GITHUB_HOST \
         --github-org $GITHUB_ORG \
