updates for ocop

diff --git a/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2 b/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2
--- a/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-cis-compliance.yml.j2
@@ -17,19 +17,10 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
-      type: string
-      default: ""
     - name: avp_aws_secret_region
       type: string
     - name: argocd_url
       type: string
-    - name: argocd_username
-      type: string
-      default: ""
-    - name: argocd_password
-      type: string
-      default: ""
   stepTemplate:
     name: gitops-cis-compliance
     env:
@@ -45,21 +36,16 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
       - name: ARGOCD_URL
         value: $(params.argocd_url)
-      - name: ARGOCD_USERNAME
-        value: $(params.argocd_username)
-      - name: ARGOCD_PASSWORD
-        value: $(params.argocd_password)
     envFrom:
       - configMapRef:
-        name: environment-properties
+          name: environment-properties
+          optional: true
       - secretRef:
-        name: secure-properties
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -68,14 +54,16 @@ spec:
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed"
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
         
         echo "Set k8s context"
diff --git a/tekton/src/tasks/gitops/gitops-cluster.yml.j2 b/tekton/src/tasks/gitops/gitops-cluster.yml.j2
--- a/tekton/src/tasks/gitops/gitops-cluster.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-cluster.yml.j2
@@ -9,10 +9,7 @@ spec:
       type: string
     - name: account
       type: string
-    - name: rosa_token
-      type: string
-      default: ""
-    - name: rosa_cluster_admin_password
+    - name: cluster_url
       type: string
       default: ""
     - name: secrets_path
@@ -25,23 +22,8 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
-      type: string
-      default: ""
     - name: git_commit_msg
       type: string
-    - name: artifactory_username
-      type: string
-      default: ""
-    - name: artifactory_token
-      type: string
-      default: ""
-    - name: icr_username
-      type: string
-      default: ""
-    - name: icr_password
-      type: string
-      default: ""
     - name: mas_catalog_version
       type: string
       default: ""
@@ -49,12 +31,6 @@ spec:
       type: string
       default: ""
     - name: common_services_channel
-      type: string
-      default: ""
-    - name: avp_aws_access_key
-      type: string
-      default: ""
-    - name: avp_aws_secret_key
       type: string
       default: ""
     - name: avp_aws_secret_region
@@ -67,12 +43,6 @@ spec:
       default: "install"
     - name: argocd_url
       type: string
-    - name: argocd_username
-      type: string
-      default: ""
-    - name: argocd_password
-      type: string
-      default: ""
   stepTemplate:
     name: gitops-cluster
     env:
@@ -80,10 +50,8 @@ spec:
         value: $(params.cluster_name)
       - name: ACCOUNT
         value: $(params.account)
-      - name: ROSA_TOKEN
-        value: $(params.rosa_token)
-      - name: ROSA_CLUSTER_ADMIN_PASSWORD
-        value: $(params.rosa_cluster_admin_password)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: SECRET_PATH
         value: $(params.secrets_path)
       - name: GIT_BRANCH
@@ -96,28 +64,14 @@ spec:
         value: $(params.github_repo)
       - name: GIT_COMMIT_MSG
         value: $(params.git_commit_msg)
-      - name: ARTIFACTORY_USERNAME
-        value: $(params.artifactory_username)
-      - name: ARTIFACTORY_TOKEN
-        value: $(params.artifactory_token)
-      - name: ICR_USERNAME
-        value: $(params.icr_username)
-      - name: ICR_PASSWORD
-        value: $(params.icr_password)
       - name: MAS_CATALOG_VERSION
         value: $(params.mas_catalog_version)
       - name: MAS_CATALOG_IMAGE
         value: $(params.mas_catalog_image)
       - name: COMMON_SERVICES_CHANNEL
         value: $(params.common_services_channel)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
       - name: MAS_CATALOG_ACTION
         value: $(params.mas_catalog_action)
       - name: COMMON_SERVICES_ACTION
@@ -126,15 +80,12 @@ spec:
         value: $(params.avp_aws_secret_region)
       - name: ARGOCD_URL
         value: $(params.argocd_url)
-      - name: ARGOCD_USERNAME
-        value: $(params.argocd_username)
-      - name: ARGOCD_PASSWORD
-        value: $(params.argocd_password)
     envFrom:
       - configMapRef:
-        name: environment-properties
+          name: environment-properties
+          optional: true
       - secretRef:
-        name: secure-properties
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -148,6 +99,13 @@ spec:
           export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
           export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
           oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
           OC_RC=$?
           if [ $OC_RC -ne 0 ]; then
             echo "oc login failed"
diff --git a/tekton/src/tasks/gitops/gitops-dro.yml.j2 b/tekton/src/tasks/gitops/gitops-dro.yml.j2
--- a/tekton/src/tasks/gitops/gitops-dro.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-dro.yml.j2
@@ -9,16 +9,13 @@ spec:
       type: string
     - name: account
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
     - name: secrets_path
       type: string
     - name: avp_aws_secret_region
       type: string
-    - name: avp_aws_secret_key
-      type: string
-      default: ""
-    - name: avp_aws_access_key
-      type: string
-      default: ""
     - name: git_branch
       type: string
     - name: github_org
@@ -27,17 +24,8 @@ spec:
       type: string
     - name: github_host
       type: string
-    - name: github_pat
-      type: string
-      default: ""
     - name: argocd_url
       type: string
-    - name: argocd_username
-      type: string
-      default: ""
-    - name: argocd_password
-      type: string
-      default: ""
   stepTemplate:
     name: gitops-dro
     env:
@@ -45,14 +33,12 @@ spec:
         value: $(params.cluster_name)
       - name: ACCOUNT
         value: $(params.account)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: SECRET_PATH
         value: $(params.secrets_path)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
       - name: GIT_BRANCH
         value: $(params.git_branch)
       - name: GITHUB_ORG
@@ -61,19 +47,14 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: GITHUB_PAT
-        value: $(params.github_pat)
       - name: ARGOCD_URL
         value: $(params.argocd_url)
-      - name: ARGOCD_USERNAME
-        value: $(params.argocd_username)
-      - name: ARGOCD_PASSWORD
-        value: $(params.argocd_password)
     envFrom:
       - configMapRef:
-        name: environment-properties
+          name: environment-properties
+          optional: true
       - secretRef:
-        name: secure-properties
+          name: secure-properties
   steps:
     - args:
       - |-
@@ -82,14 +63,34 @@ spec:
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed"
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
         
         echo "Set k8s context"
