Add changes for mas-apps

diff --git a/tekton/src/tasks/gitops/gitops-cp4d-service.yml.j2 b/tekton/src/tasks/gitops/gitops-cp4d-service.yml.j2
--- a/tekton/src/tasks/gitops/gitops-cp4d-service.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-cp4d-service.yml.j2
@@ -7,6 +7,9 @@ spec:
   params:
     - name: cluster_name
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
     - name: account
       type: string
     - name: git_branch
@@ -31,12 +34,16 @@ spec:
       type: string
     - name: cpd_service_storage_class
       type: string
-
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-cp4d-service
     env:
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: ACCOUNT
         value: $(params.account)
       - name: GITHUB_REPO
@@ -63,6 +70,8 @@ spec:
         value: $(params.cpd_service_block_storage_class)
       - name: CPD_SERVICE_STORAGE_CLASS
         value: $(params.cpd_service_storage_class)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
     envFrom:
       - configMapRef:
           name: environment-properties
@@ -77,18 +86,47 @@ spec:
         git config --global user.password $GITHUB_PAT
         
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed"
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          echo "oc login : via ROSA_CONFIG"
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed to $OCP_SERVER"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          echo "oc login : OCP_USERNAME=$OCP_USERNAME OCP_SERVER=$OCP_SERVER OCP_PASSWORD=${OCP_PASSWORD:0:8}<snip> ..."
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          echo "oc login : via ocp_login"
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
         
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
+
+        if [ -z $ARGOCD_URL ] || [ -z $ARGOCD_USERNAME ] || [ -z $ARGOCD_PASSWORD ]; then
+          export ARGOCD_URL=$(oc get route  openshift-gitops-server -n openshift-gitops -ojsonpath='{.spec.host}' --context $K8S_AUTH_CONTEXT)
+          export ARGOCD_USERNAME=admin
+          export ARGOCD_PASSWORD=$(oc get secret openshift-gitops-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' --context $K8S_AUTH_CONTEXT | base64 -d ; echo)
+        fi
 
         export MAS_CONFIG_DIR=/workspace/configs/$MAS_INSTANCE_ID-cp4d-service-$CPD_SERVICE_NAME
         mkdir -p /workspace/configs/$MAS_INSTANCE_ID-cp4d-service-$CPD_SERVICE_NAME
diff --git a/tekton/src/tasks/gitops/gitops-suite-objectstorage-config.yml.j2 b/tekton/src/tasks/gitops/gitops-suite-objectstorage-config.yml.j2
--- a/tekton/src/tasks/gitops/gitops-suite-objectstorage-config.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-suite-objectstorage-config.yml.j2
@@ -7,6 +7,9 @@ spec:
   params:
     - name: cluster_name
       type: string
+    - name: cluster_url
+      type: string
+      default: ""
     - name: account
       type: string
     - name: secrets_path
@@ -23,12 +26,16 @@ spec:
       type: string
     - name: avp_aws_secret_region
       type: string
-
+    - name: argocd_url
+      type: string
+      default: ""
   stepTemplate:
     name: gitops-suite-objectstorage-config
     env:
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
+      - name: OCP_SERVER
+        value: $(params.cluster_url)
       - name: ACCOUNT
         value: $(params.account)
       - name: SECRET_PATH
@@ -45,6 +52,8 @@ spec:
         value: $(params.github_repo)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
+      - name: ARGOCD_URL
+        value: $(params.argocd_url)
     envFrom:
       - configMapRef:
           name: environment-properties
@@ -62,14 +71,37 @@ spec:
         git config --global user.password $GITHUB_PAT
 
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
-        export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
-        export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
-        export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
-        oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-        OC_RC=$?
-        if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed to $OCP_SERVER"
-          exit 1
+        if [ -f $ROSA_CONFIG ]; then
+          echo "oc login : via ROSA_CONFIG"
+          export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
+          export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
+          export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
+          oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed to $OCP_SERVER"
+            exit 1
+          fi
+        elif [ -n $OCP_SERVER ]; then
+          echo "oc login : OCP_USERNAME=$OCP_USERNAME OCP_SERVER=$OCP_SERVER OCP_PASSWORD=${OCP_PASSWORD:0:8}<snip> ..."
+          oc login -u $OCP_USERNAME -p $OCP_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
+        else
+          echo "oc login : via ocp_login"
+          aws configure set aws_access_key_id $SM_AWS_ACCESS_KEY_ID
+          aws configure set aws_secret_access_key $SM_AWS_SECRET_ACCESS_KEY
+          aws configure set default.region $SM_AWS_REGION
+          export CLUSTER_TYPE=rosa
+          ROLE_NAME=ocp_login ansible-playbook ibm.mas_devops.run_role 
+          OC_RC=$?
+          if [ $OC_RC -ne 0 ]; then
+            echo "oc login failed"
+            exit 1
+          fi
         fi
         
         echo "Set k8s context"
