register sendgrid subuser credentials in AWS SM

diff --git a/tekton/src/tasks/gitops/gitops-suite-smtp-config-sendgrid.yml.j2 b/tekton/src/tasks/gitops/gitops-suite-smtp-config-sendgrid.yml.j2
--- a/tekton/src/tasks/gitops/gitops-suite-smtp-config-sendgrid.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-suite-smtp-config-sendgrid.yml.j2
@@ -97,8 +97,8 @@ spec:
         git config --global user.email "you@example.com"
         git config --global user.password "${GITHUB_PAT}"
 
-        API_KEY_OUTPUT_FILE="/tmp/init-suite-smtp-config/sendgrid-api-key"
-        rm "${API_KEY_OUTPUT_FILE}"
+        OUTPUT_FILE="/tmp/init-suite-smtp-config/mas-saas-sendgrid-subuser-output.yaml"
+        rm "${OUTPUT_FILE}"
 
         mas-saas-sendgrid-subuser \
           --customer-id "${ICN}" \
@@ -107,41 +107,79 @@ spec:
           --mas-cluster-id "${CLUSTER_ID}" \
           --mas-instance-id "${MAS_INSTANCE_ID}" \
           --cis-crn "${CIS_CRN}" \
-          --api-key-output-file "${API_KEY_OUTPUT_FILE}"\
+          --output-file "${OUTPUT_FILE}"\
           --action create
         
         rc="$?"
 
+        # Pull values out of the outfile and set them as environment vars
+        if [[ -f "${OUTPUT_FILE}" ]]; then
+          echo "Reading outputs from ${OUTPUT_FILE}"
+          export SUBUSER_USERNAME="$(yq '.subuser.username // ""' "${OUTPUT_FILE}")"
+          export SUBUSER_PASSWORD="$(yq '.subuser.password // ""' "${OUTPUT_FILE}")"
+          export SENDGRID_APIKEY_PASSWORD="$(yq '.apikey // ""' "${OUTPUT_FILE}")"
+        fi
+
         # If an API key was generated by the script (even if something went wrong in later step)
         # this is our only opportunity to obtain its value so we need to register it in secrets manager now
         # so it'll be present when whatever the issue is resolved and the instance pipeline is rerun
-        if [[ -f "${API_KEY_OUTPUT_FILE}" ]]; then
+        update_apikey_secret_rc="0"
+        if [[ -n "${SENDGRID_APIKEY_PASSWORD}" ]]; then
           SECRET_NAME_SMTP="${ACCOUNT_ID}/${CLUSTER_ID}/${MAS_INSTANCE_ID}/smtp"
-          echo "Reading generated API Key from ${API_KEY_OUTPUT_FILE} and setting it in AWS secrets manager"
+          echo "Putting generated API Key in ${SECRET_NAME_SMTP}"
 
           # NOTE: deliberately not using $SMTP_USERNAME or $SMTP_PASSWORD here, since we don't need/want the gitops-mas-config to repeat this step
           SENDGRID_APIKEY_USERNAME="apikey"
           SENDGRID_APIKEY_PASSWORD="$(cat ${API_KEY_OUTPUT_FILE})"
-          TAGS="[{\"Key\": \"source\", \"Value\": \"gitops_mas_config\"}, {\"Key\": \"account\", \"Value\": \"${ACCOUNT_ID}\"}, {\"Key\": \"cluster\", \"Value\": \"${CLUSTER_ID}\"}]"
+          TAGS="[{\"Key\": \"source\", \"Value\": \"gitops_suite_smtp_config_sendgrid\"}, {\"Key\": \"account\", \"Value\": \"${ACCOUNT_ID}\"}, {\"Key\": \"cluster\", \"Value\": \"${CLUSTER_ID}\"}]"
           # NOTE: running function in a subshell so we don't exit this script if something goes wrong (necessary due to the use of "set +o pipefail" in sm_update_secret)
           (sm_update_secret "${SECRET_NAME_SMTP}" "{\"username\": \"$SENDGRID_APIKEY_USERNAME\", \"password\": \"$SENDGRID_APIKEY_PASSWORD\"}" "${TAGS}")
-          update_rc="$?"
-          if [[ "${update_rc}" != "0" ]]; then
-            # We could add additional automation to deal with the (rare) edge case of the SM update failing intermittently.
-            # i.e. add a "force_regenerate_api_key" flag that can be set before rerunning the pipeline
-            # but I think - given the rarity - just documenting the manual resolution steps below will suffice.
-            # another mitigation would be to add retry logic to the sm_update_secret call above
-            echo "Failed to write generated API Key to AWS Secrets Manager!"
-            echo "The API Key value is now lost and cannot be retrieved, manual intervention is required before rerunning the pipeline:"
-            echo "  - Log in to the SendGrid parent account"
-            echo "  - Switch to the subuser's account (which will start with ${ICN}, the full value will be in the logs above)"
-            echo "  - Locate and delete the API Key for this MAS instance - its name will be in the logs above"
-            echo "  - A new API Key for the MAS instance will be generated by this Task in the next pipeline run"
-            exit 1
-          fi
 
-
+          # defer exiting the script if the sm_update_secret call above failed, so we have an opportunity to register other generated secrets
+          update_apikey_secret_rc="$?"
         fi
+
+        # If a new subuser was created by the script (even if something went wrong in a later step)
+        # this is our only opportunity to store the password we generated for the subuser
+        update_subuser_secret_rc=""
+        if [[ -n "${SUBUSER_PASSWORD}" ]]; then
+          SECRET_NAME_SENDGRID="${ICN}/sendgrid_subuser"
+          TAGS="[{\"Key\": \"source\", \"Value\": \"gitops_suite_smtp_config_sendgrid\"}"
+          echo "Putting generated subuser credentials in ${SECRET_NAME_SENDGRID}"
+          (sm_update_secret "${SECRET_NAME_SMTP}" "{\"username\": \"$SUBUSER_USERNAME\", \"password\": \"$SUBUSER_PASSWORD\"}" "${TAGS}")
+
+          # defer exiting the script if the sm_update_secret call above failed, so we have an opportunity to register other generated secrets
+          update_subuser_secret_rc="$?"
+        fi
+
+        if [[ "${update_apikey_secret_rc}" != "0" ]]; then
+          # We could add additional automation to deal with the (rare) edge case of the SM update failing.
+          # i.e. add a "force_regenerate_api_key" flag that can be set before rerunning the pipeline
+          # but I think - given the rarity - just documenting the manual resolution steps below will suffice.
+          # another mitigation would be to add retry logic to the sm_update_secret call above
+          echo "Failed to write generated API Key to AWS Secrets Manager!"
+          echo "The API Key value is now lost and cannot be retrieved, manual intervention is required before rerunning the pipeline:"
+          echo "  - Log in to the SendGrid parent account"
+          echo "  - Switch to the subuser's account (which will start with ${ICN}, the full value will be in the logs above)"
+          echo "  - Locate and delete the API Key for this MAS instance - its name will be in the logs above"
+          echo "  - A new API Key for the MAS instance will be generated by this Task in the next pipeline run"
+          rc="${update_apikey_secret_rc}"
+        fi
+
+
+
+        if [[ "${update_subuser_secret_rc} != "0" ]]; then
+          # We could add additional automation to deal with the (rare) edge case of the SM update failing.
+          # but I think - given the rarity - just documenting the manual resolution steps below will suffice.
+          echo "Failed to write generated subuser username and password to AWS Secrets Manager!"
+          echo "The generated password value is now lost and cannot be retrieved, manual intervention is required before rerunning the pipeline:"
+          echo "  - Log in to the SendGrid parent account"
+          echo "  - Go to Settings -> Subuser management"
+          echo "  - Locate and delete the subuser generated by the script above. The username will start with ${ICN}, the full value will be in the logs above."
+          echo "  - A new subuser will be created for the customer in the next pipeline run"
+          rc="${update_subuser_secret_rc}"
+        fi
+
 
         if [[ "${rc}" != "0" ]]; then
           echo "mas-saas-sendgrid-subuser failed with rc ${rc}"
