[patch] Add dro and dro config

diff --git a/tekton/src/tasks/gitops/gitops-dro.yml.j2 b/tekton/src/tasks/gitops/gitops-dro.yml.j2
--- a/tekton/src/tasks/gitops/gitops-dro.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-dro.yml.j2
@@ -2,22 +2,13 @@
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
-  name: gitops-deprovision-suite-workspace
+  name: gitops-dro
 spec:
   params:
     - name: cluster_name
       type: string
     - name: account
       type: string
-    - name: secrets_path
-      type: string
-    - name: mas_instance_id
-      type: string
-    - name: workspace_id
-      type: string
-    - name: workspace_name
-      type: string
-      default: aws
     - name: git_branch
       type: string
     - name: github_org
@@ -28,17 +19,13 @@ spec:
       type: string
     - name: github_pat
       type: string
-    - name: force_removal
-      type: string
   stepTemplate:
-    name: gitops-deprovision-suite-workspace
+    name: gitops-dro
     env:
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
       - name: ACCOUNT
         value: $(params.account)
-      - name: MAS_INSTANCE_ID
-        value: $(params.mas_instance_id)
       - name: GIT_BRANCH
         value: $(params.git_branch)
       - name: GITHUB_ORG
@@ -47,20 +34,11 @@ spec:
         value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: WORKSPACE_ID
-        value: $(params.workspace_id)
-      - name: WORKSPACE_NAME
-        value: $(params.workspace_name)
       - name: GITHUB_PAT
-        value: $(params.github_pat) 
-      - name: FORCE_REMOVAL
-        value: $(params.force_removal)
+        value: $(params.github_pat)
   steps:
     - args:
       - |-
-
-        mkdir -p /tmp/deprovision-suite-workspace
-
         git config --global user.name "MAS Automation"
         git config --global user.email "you@example.com"
         git config --global user.password $GITHUB_PAT
@@ -72,32 +50,30 @@ spec:
         oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
         OC_RC=$?
         if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed so assume there is no suit workspace to deprovision, exiting.."
-          exit 0
+          echo "oc login failed"
+          exit 1
         fi
+        
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
 
-        if [ -z $ARGOCD_URL ] || [ -z $ARGOCD_USERNAME ] || [ -z $ARGOCD_PASSWORD ]; then
-          export ARGOCD_URL=$(oc get route  openshift-gitops-server -n openshift-gitops -ojsonpath='{.spec.host}' --context $K8S_AUTH_CONTEXT)
-          export ARGOCD_USERNAME=admin
-          export ARGOCD_PASSWORD=$(oc get secret openshift-gitops-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' --context $K8S_AUTH_CONTEXT | base64 -d ; echo)
-        fi
+        export ARGOCD_URL=$(oc get route  openshift-gitops-server -n openshift-gitops -ojsonpath='{.spec.host}' --context $K8S_AUTH_CONTEXT)
+        export ARGOCD_USERNAME=admin
+        export ARGOCD_PASSWORD=$(oc get secret openshift-gitops-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' --context $K8S_AUTH_CONTEXT | base64 -d ; echo)
 
-        mas gitops-deprovision-suite-workspace -a $ACCOUNT -c $CLUSTER_NAME -m $MAS_INSTANCE_ID \
-        --mas-workspace-id $WORKSPACE_ID \
-        --mas-workspace-name $WORKSPACE_NAME \
-        --dir /tmp/deprovision-suite-workspace \
+        mkdir -p /tmp/init-dro
+        mas gitops-dro -a $ACCOUNT -c $CLUSTER_NAME \
+        --dir /tmp/init-dro \
         --github-push \
         --github-host $GITHUB_HOST \
-        --github-org $GITHUB_ORG \
+        --github-org  $GITHUB_ORG \
         --github-repo $GITHUB_REPO \
         --git-branch $GIT_BRANCH
       command:
         - /bin/sh
         - -c
-      name: gitops-deprovision-suite-workspace
-      imagePullPolicy: Always
+      name: gitops-dro
+      imagePullPolicy: IfNotPresent
       image: quay.io/ibmmas/cli:7.7.0-pre.gitops
   workspaces:
     - name: configs
