Add mas-apps pipeline and taskls

diff --git a/tekton/src/tasks/gitops/gitops-db2u.yml.j2 b/tekton/src/tasks/gitops/gitops-db2u.yml.j2
--- a/tekton/src/tasks/gitops/gitops-db2u.yml.j2
+++ b/tekton/src/tasks/gitops/gitops-db2u.yml.j2
@@ -2,97 +2,80 @@
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
-  name: gitops-deprovision-cluster
+  name: gitops-db2u
 spec:
   params:
     - name: cluster_name
       type: string
     - name: account
       type: string
-    - name: secrets_path
-      type: string
-    - name: git_branch
-      type: string
-    - name: github_org
-      type: string
     - name: github_repo
       type: string
-    - name: github_host
-      type: string
-    - name: github_pat
-      type: string
-    - name: avp_aws_access_key
-      type: string
-    - name: avp_aws_secret_key
+    - name: secrets_path
       type: string
     - name: avp_aws_secret_region
       type: string
+    - name: avp_aws_secret_key
+      type: string
+    - name: avp_aws_access_key
+      type: string
+    - name: db2_channel
+      type: string
   stepTemplate:
-    name: gitops-deprovision-cluster
+    name: gitops-db2u
     env:
       - name: CLUSTER_NAME
         value: $(params.cluster_name)
       - name: ACCOUNT
         value: $(params.account)
-      - name: SECRET_PATH
-        value: $(params.secrets_path)
-      - name: GIT_BRANCH
-        value: $(params.git_branch)
-      - name: GITHUB_ORG
-        value: $(params.github_org)
-      - name: GITHUB_HOST
-        value: $(params.github_host)
       - name: GITHUB_REPO
         value: $(params.github_repo)
-      - name: SM_AWS_ACCESS_KEY_ID
-        value: $(params.avp_aws_access_key)
-      - name: SM_AWS_SECRET_ACCESS_KEY
-        value: $(params.avp_aws_secret_key)
+      - name: SECRET_PATH
+        value: $(params.secrets_path)
       - name: SM_AWS_REGION
         value: $(params.avp_aws_secret_region)
-      - name: GITHUB_PAT
-        value: $(params.github_pat) 
+      - name: SM_AWS_SECRET_ACCESS_KEY
+        value: $(params.avp_aws_secret_key)
+      - name: SM_AWS_ACCESS_KEY_ID
+        value: $(params.avp_aws_access_key)
+      - name: DB2_CHANNEL
+        value: $(params.db2_channel)
   steps:
     - args:
       - |-
         git config --global user.name "MAS Automation"
         git config --global user.email "you@example.com"
         git config --global user.password $GITHUB_PAT
-
+        
         ROSA_CONFIG=/workspace/configs/tmp-rosa/rosa-$(params.cluster_name)-details.yaml
         export OCP_SERVER=$(cat $ROSA_CONFIG | yq -r '.data.api_url')
         export OCP_USERNAME=$(cat $ROSA_CONFIG | yq -r '.data.username')
         export ROSA_CLUSTER_ADMIN_PASSWORD=$(cat $ROSA_CONFIG | yq -r '.data.admin_password')
         oc login -u $OCP_USERNAME -p $ROSA_CLUSTER_ADMIN_PASSWORD $OCP_SERVER --insecure-skip-tls-verify
-
         OC_RC=$?
         if [ $OC_RC -ne 0 ]; then
-          echo "oc login failed so assume there is no cluster to deprovision, exiting.."
-          exit 0
+          echo "oc login failed"
+          exit 1
         fi
-
+        
         echo "Set k8s context"
         export K8S_AUTH_CONTEXT=$(oc whoami -c)
-        
-        if [ -z $ARGOCD_URL ] || [ -z $ARGOCD_USERNAME ] || [ -z $ARGOCD_PASSWORD ]; then
-          export ARGOCD_URL=$(oc get route  openshift-gitops-server -n openshift-gitops -ojsonpath='{.spec.host}' --context $K8S_AUTH_CONTEXT)
-          export ARGOCD_USERNAME=admin
-          export ARGOCD_PASSWORD=$(oc get secret openshift-gitops-cluster -n openshift-gitops -ojsonpath='{.data.admin\.password}' --context $K8S_AUTH_CONTEXT | base64 -d ; echo)
-        fi
 
-        mkdir -p /tmp/deprovision-cluster
-        mas gitops-deprovision-cluster -a $ACCOUNT -c $CLUSTER_NAME \
-        --dir /tmp/deprovision-cluster \
+        mkdir -p /tmp/init-db2u
+        mas gitops-db2u -a $ACCOUNT -c $CLUSTER_NAME \
+        --dir /tmp/init-db2u \
+        --secrets-path $SECRET_PATH \
         --github-push \
         --github-host $GITHUB_HOST \
         --github-org  $GITHUB_ORG \
         --github-repo $GITHUB_REPO \
-        --git-branch $GIT_BRANCH \
-        --secrets-path $SECRET_PATH
+        --git-branch $GIT_BRANCH
+
+        exit $?
       command:
         - /bin/sh
         - -c
-      name: gitops-deprovision-cluster
+      name: gitops-db2u-database
       imagePullPolicy: IfNotPresent
       image: quay.io/ibmmas/cli:7.7.0-pre.ajw-mascore937
   workspaces:
